/* GIGANT MEDIA — multilingual content dictionary
   Default: Russian. Extend by adding keys to all locales. */
window.GM_CONTENT = {
  defaultLang: "ru",
  langs: ["ru", "en", "uz"],
  meta: {
    ru: {
      title: "GIGANT MEDIA — Рекламное производство полного цикла",
      description:
        "GIGANT MEDIA — рекламно-производственная компания полного цикла в Узбекистане: вывески, ПОСМ, печать, мебель, стенды. 15+ лет, своё производство, филиалы по стране.",
    },
    en: {
      title: "GIGANT MEDIA — Full-cycle advertising production",
      description:
        "GIGANT MEDIA is a full-cycle advertising and production company in Uzbekistan: signs, POSM, print, furniture, stands. 15+ years, in-house production, nationwide coverage.",
    },
    uz: {
      title: "GIGANT MEDIA — To‘liq tsikli reklama ishlab chiqarish",
      description:
        "GIGANT MEDIA — O‘zbekistondagi to‘liq tsikli reklama-ishlab chiqarish kompaniyasi: yorliqlar, POSM, bosma, mebel, stendlar. 15+ yil, o‘z ishlab chiqarish, butun mamlakat bo‘ylab filiallar.",
    },
  },
  dict: {
    ru: {
      "nav.home": "Главная",
      "nav.about": "О компании",
      "nav.services": "Услуги",
      "nav.cases": "Кейсы",
      "nav.advantages": "Преимущества",
      "nav.reviews": "Отзывы",
      "nav.faq": "FAQ",
      "nav.contacts": "Контакты",
      "nav.clients": "Клиенты",
      "nav.cta": "Оставить заявку",
      "nav.menu": "Основное меню",
      "nav.open": "Открыть меню",

      "hero.eyebrow": "Рекламное производство · Узбекистан",
      "hero.title": "Производим рекламу, которая работает",
      "hero.lead":
        "GIGANT MEDIA — полный цикл: дизайн, производство и монтаж. Вывески, ПОСМ, печать, мебель и оформление объектов по всему Узбекистану.",
      "hero.cta1": "Рассчитать проект",
      "hero.cta2": "Смотреть кейсы",
      "hero.chip1": "15+ лет на рынке",
      "hero.chip2": "1500 проектов / год",
      "hero.chip3": "Собственное производство",
      "hero.float1": "85 специалистов",
      "hero.float2": "1500 м² площадей",
      "hero.imgAlt": "Производство рекламной продукции GIGANT MEDIA",

      "about.eyebrow": "Компания",
      "about.title": "О компании",
      "about.p1":
        "Рекламно-производственная компания полного цикла «GIGANT MEDIA» успешно работает на рекламном рынке более 15 лет и предлагает весь комплекс рекламных, полиграфических и дизайнерских услуг на высоком профессиональном уровне.",
      "about.p2":
        "За плечами — богатый опыт производства наружной рекламы. Многие фасады зданий, офисов и магазинов выглядят по-новому благодаря нашим специалистам. Филиалы открыты по всему Узбекистану.",
      "about.geo": "География присутствия",

      "services.eyebrow": "Услуги",
      "services.title": "13 направлений полного цикла",
      "services.lead":
        "Каждая услуга — понятное коммерческое решение с фото реального производства.",
      "services.more": "Подробнее →",
      "services.note": "Гарантийное обслуживание и консультации — даже после сдачи проекта.",
      "services.prev": "Назад",
      "services.next": "Вперёд",
      "services.s1.t": "Вывески",
      "services.s1.d": "Объёмные буквы, световые короба и фасадные конструкции с монтажом.",
      "services.s1.b": "Монтаж под ключ",
      "services.s2.t": "ПОСМ",
      "services.s2.d": "Шелфтокеры, стопперы, диспенсеры и материалы для точки продаж.",
      "services.s2.b": "Рост внимания к SKU",
      "services.s3.t": "Придорожная реклама",
      "services.s3.d": "Щиты, конструкции и носители вдоль транспортных артерий.",
      "services.s3.b": "Максимальный охват",
      "services.s4.t": "Мебель",
      "services.s4.d": "Торговая и выставочная мебель под бренд и задачу объекта.",
      "services.s4.b": "Под ваш бренд",
      "services.s5.t": "Воблеры",
      "services.s5.d": "POS-элементы, которые привлекают внимание к товару на полке.",
      "services.s5.b": "Быстрый акцент",
      "services.s6.t": "Мобильные стенды",
      "services.s6.d": "Конструкции для акций, форумов и выездных мероприятий.",
      "services.s6.b": "Сборка на месте",
      "services.s7.t": "Декор",
      "services.s7.d": "Декоративные решения для интерьеров, витрин и бренд-зон.",
      "services.s7.b": "Атмосфера объекта",
      "services.s8.t": "Порошковая покраска",
      "services.s8.d": "Стойкое покрытие металлоконструкций и рекламных изделий.",
      "services.s8.b": "Долговечность",
      "services.s9.t": "Комплексное оформление",
      "services.s9.d": "Полный цикл оформления объекта: от концепции до монтажа.",
      "services.s9.b": "Один подрядчик",
      "services.s10.t": "Рекламная оклейка",
      "services.s10.d": "Брендирование транспорта, витрин и поверхностей плёнкой.",
      "services.s10.b": "Точный цвет",
      "services.s11.t": "Широкоформатная печать",
      "services.s11.d": "Баннеры, бренд-зоны, интерьерная и наружная графика.",
      "services.s11.b": "Контроль печати",
      "services.s12.t": "Сувениры и награды",
      "services.s12.d": "Корпоративные подарки, награды и сувенирная продукция.",
      "services.s12.b": "Имидж бренда",
      "services.s13.t": "Выставочные стенды",
      "services.s13.d": "Выставочные стенды и конструкции под ключ.",
      "services.s13.b": "Готово к показу",

      "clients.eyebrow": "Клиенты",
      "clients.title": "Нам доверяют",
      "clients.lead": "Бренды и компании, для которых мы производим рекламу по всему Узбекистану.",

      "cases.eyebrow": "Кейсы",
      "cases.title": "Результаты вместо сухого портфолио",
      "cases.lead": "Задача, решение и измеримый эффект — так мы показываем работу.",
      "cases.c1.client": "Ритейл",
      "cases.c1.title": "Оформление торговой зоны",
      "cases.c1.d": "Комплексная бренд-зона: вывеска, навигация и POSM в едином стиле.",
      "cases.c1.m1": "14 дней",
      "cases.c1.m1l": "срок реализации",
      "cases.c1.m2": "1 подрядчик",
      "cases.c1.m2l": "дизайн → монтаж",
      "cases.c2.client": "Банк",
      "cases.c2.title": "Фасад и входная группа",
      "cases.c2.d": "Световые конструкции и оклейка с контролем цвета и сроков.",
      "cases.c3.client": "HoReCa",
      "cases.c3.title": "Интерьерная графика",
      "cases.c3.d": "Декор и печать для атмосферы заведения без остановки работы.",
      "cases.link": "Смотреть кейс →",

      "process.eyebrow": "Процесс",
      "process.title": "Как мы работаем",
      "process.lead": "Прозрачные этапы: от расчёта до гарантийного сопровождения.",
      "process.1.t": "Бриф и расчёт",
      "process.1.d": "Фиксируем задачу, сроки, бюджет и технические ограничения.",
      "process.2.t": "Дизайн и инженерия",
      "process.2.d": "Дизайн-отдел и технолог готовят решение под производство.",
      "process.3.t": "Производство",
      "process.3.d": "Печать, металлоконструкции, покраска и сборка на своих площадях.",
      "process.4.t": "Монтаж и сервис",
      "process.4.d": "Установка на объекте и консультации после сдачи проекта.",

      "numbers.eyebrow": "Масштаб",
      "numbers.title": "О нас в цифрах",
      "numbers.lead": "Производственная компания с присутствием по регионам Узбекистана.",
      "numbers.1": "проектов в год",
      "numbers.2": "сотрудников в команде",
      "numbers.3": "лет на рекламном рынке",
      "numbers.4": "производственных площадей",

      "advantages.eyebrow": "Преимущества",
      "advantages.title": "Почему выбирают GIGANT MEDIA",
      "advantages.lead": "Свой цех, свой дизайн и ответственность за результат.",
      "advantages.1.chip": "Производство",
      "advantages.1.t": "Собственный цех",
      "advantages.1.d": "Оптимальная стоимость и сжатые сроки без лишних подрядных звеньев.",
      "advantages.2.chip": "Экспертиза",
      "advantages.2.t": "Индивидуальный подход",
      "advantages.2.d": "Технолог помогает оптимизировать конструкцию, бюджет и сроки.",
      "advantages.3.chip": "Дизайн",
      "advantages.3.t": "Свой дизайн-отдел",
      "advantages.3.d": "Профессиональные макеты и визуалы под любую продукцию.",

      "reviews.eyebrow": "Отзывы",
      "reviews.title": "Слова клиентов",
      "reviews.lead": "Качество, скорость обработки заказа и предсказуемая цена.",
      "reviews.1.chip": "Клиент",
      "reviews.1.q": "«Отличное качество, скорость обработки заказа на высоте. Приемлемые цены. Обязательно обращусь снова.»",
      "reviews.1.n": "Рамиль Ринатович",
      "reviews.1.r": "Директор компании",
      "reviews.2.chip": "Производство",
      "reviews.2.q": "«Важно, что есть свой цех и дизайн: меньше согласований, быстрее выход на монтаж.»",
      "reviews.2.n": "B2B-клиент",
      "reviews.2.r": "Ритейл / оформление",
      "reviews.3.chip": "Сервис",
      "reviews.3.q": "«После сдачи проекта продолжают консультировать — это редкость и сильный аргумент.»",
      "reviews.3.n": "Партнёр",
      "reviews.3.r": "Комплексное оформление",

      "faq.eyebrow": "FAQ",
      "faq.title": "Частые вопросы",
      "faq.lead": "Коротко о сроках, производстве и том, как стартовать проект.",
      "faq.1.q": "Сколько занимает типовой проект?",
      "faq.1.a": "От нескольких дней для печати и POSM до 2–4 недель для комплексного оформления — сроки фиксируем на этапе расчёта.",
      "faq.2.q": "У вас своё производство?",
      "faq.2.a": "Да. Собственный цех, дизайн-отдел и монтажные бригады — это контроль качества, сроков и стоимости.",
      "faq.3.q": "Работаете ли вы в регионах?",
      "faq.3.a": "Да. Филиалы и проекты по всему Узбекистану: Ташкент, область и ключевые города.",
      "faq.4.q": "Как оставить заявку?",
      "faq.4.a": "Заполните форму на сайте, позвоните или напишите в WhatsApp / Telegram — менеджер свяжется в рабочее время.",

      "contacts.eyebrow": "Контакты",
      "contacts.title": "Получить консультацию",
      "contacts.lead": "Оставьте контакты — уточним задачу, сроки и бюджет.",
      "contacts.phone": "Телефон",
      "contacts.more": "Дополнительно",
      "contacts.address": "Адрес",
      "contacts.addressValue": "г. Ташкент, Юнусабадский район, 9 квартал, ул. Юкори Каракамыш, 5А",
      "contacts.quick": "Быстрая связь",
      "contacts.whatsapp": "WhatsApp",
      "contacts.telegram": "Telegram",
      "contacts.email": "Email",
      "form.name": "Имя",
      "form.namePh": "Как к вам обращаться",
      "form.phone": "Телефон",
      "form.phonePh": "+998 __ ___ __ __",
      "form.lang": "Язык общения",
      "form.langRu": "Русский",
      "form.langUz": "Узбекский",
      "form.langEn": "English",
      "form.msg": "Задача",
      "form.msgPh": "Коротко: что нужно сделать и к какому сроку",
      "form.submit": "Оставить заявку",
      "form.note": "Нажимая кнопку, вы соглашаетесь на обработку персональных данных.",
      "form.errorName": "Укажите имя",
      "form.errorPhone": "Укажите корректный телефон",
      "form.success": "Заявка отправлена",
      "form.sending": "Отправляем…",

      "footer.tagline": "Рекламно-производственная компания полного цикла. Филиалы по всему Узбекистану.",
      "footer.menu": "Меню",
      "footer.services": "Услуги",
      "footer.contacts": "Контакты",
      "footer.copy": "© GIGANT MEDIA",
      "footer.note": "Full-cycle advertising production · Uzbekistan",
      "lang.label": "Язык сайта",
    },

    en: {
      "nav.home": "Home",
      "nav.about": "About",
      "nav.services": "Services",
      "nav.cases": "Cases",
      "nav.advantages": "Advantages",
      "nav.reviews": "Reviews",
      "nav.faq": "FAQ",
      "nav.contacts": "Contact",
      "nav.clients": "Clients",
      "nav.cta": "Request a quote",
      "nav.menu": "Main menu",
      "nav.open": "Open menu",

      "hero.eyebrow": "Advertising production · Uzbekistan",
      "hero.title": "We produce advertising that works",
      "hero.lead":
        "GIGANT MEDIA — full cycle: design, production and installation. Signs, POSM, print, furniture and object branding across Uzbekistan.",
      "hero.cta1": "Get a project estimate",
      "hero.cta2": "View cases",
      "hero.chip1": "15+ years on the market",
      "hero.chip2": "1,500 projects / year",
      "hero.chip3": "In-house production",
      "hero.float1": "85 specialists",
      "hero.float2": "1,500 m² facilities",
      "hero.imgAlt": "GIGANT MEDIA advertising production",

      "about.eyebrow": "Company",
      "about.title": "About us",
      "about.p1":
        "GIGANT MEDIA is a full-cycle advertising and production company with 15+ years on the market. We deliver advertising, print and design services at a professional quality level.",
      "about.p2":
        "We have deep experience in outdoor advertising. Facades of offices and stores look new thanks to our team. Branches are open across Uzbekistan.",
      "about.geo": "Coverage geography",

      "services.eyebrow": "Services",
      "services.title": "13 full-cycle directions",
      "services.lead": "Each service is a clear commercial offer backed by real production photos.",
      "services.more": "Learn more →",
      "services.note": "Warranty support and consulting — even after project handover.",
      "services.prev": "Previous",
      "services.next": "Next",
      "services.s1.t": "Signs",
      "services.s1.d": "Dimensional letters, lightboxes and facade structures with installation.",
      "services.s1.b": "Turnkey install",
      "services.s2.t": "POSM",
      "services.s2.d": "Shelf talkers, stoppers, dispensers and in-store materials.",
      "services.s2.b": "SKU attention",
      "services.s3.t": "Roadside ads",
      "services.s3.d": "Boards and structures along major traffic routes.",
      "services.s3.b": "Maximum reach",
      "services.s4.t": "Furniture",
      "services.s4.d": "Retail and exhibition furniture tailored to brand and space.",
      "services.s4.b": "Brand-fit build",
      "services.s5.t": "Wobblers",
      "services.s5.d": "POS elements that pull attention to products on the shelf.",
      "services.s5.b": "Fast highlight",
      "services.s6.t": "Mobile stands",
      "services.s6.d": "Structures for promotions, forums and field events.",
      "services.s6.b": "On-site setup",
      "services.s7.t": "Decor",
      "services.s7.d": "Decorative solutions for interiors, windows and brand zones.",
      "services.s7.b": "Space atmosphere",
      "services.s8.t": "Powder coating",
      "services.s8.d": "Durable coating for metal structures and advertising products.",
      "services.s8.b": "Long lifespan",
      "services.s9.t": "Complex branding",
      "services.s9.d": "Full object branding cycle: from concept to installation.",
      "services.s9.b": "One contractor",
      "services.s10.t": "Wrapping",
      "services.s10.d": "Vehicle, window and surface branding with vinyl.",
      "services.s10.b": "Color accuracy",
      "services.s11.t": "Wide-format print",
      "services.s11.d": "Banners, brand zones, indoor and outdoor graphics.",
      "services.s11.b": "Print control",
      "services.s12.t": "Souvenirs & awards",
      "services.s12.d": "Corporate gifts, awards and souvenir products.",
      "services.s12.b": "Brand image",
      "services.s13.t": "Exhibition stands",
      "services.s13.d": "Exhibition stands and structures delivered turnkey.",
      "services.s13.b": "Show-ready",

      "clients.eyebrow": "Clients",
      "clients.title": "Trusted by brands",
      "clients.lead": "Companies we produce advertising for across Uzbekistan.",

      "cases.eyebrow": "Cases",
      "cases.title": "Results instead of a flat gallery",
      "cases.lead": "Challenge, solution and measurable outcome — how we present work.",
      "cases.c1.client": "Retail",
      "cases.c1.title": "Retail zone branding",
      "cases.c1.d": "Full brand zone: signage, navigation and POSM in one system.",
      "cases.c1.m1": "14 days",
      "cases.c1.m1l": "delivery time",
      "cases.c1.m2": "1 contractor",
      "cases.c1.m2l": "design → install",
      "cases.c2.client": "Bank",
      "cases.c2.title": "Facade & entrance group",
      "cases.c2.d": "Light structures and wrapping with color and deadline control.",
      "cases.c3.client": "HoReCa",
      "cases.c3.title": "Interior graphics",
      "cases.c3.d": "Decor and print that keep the venue running during works.",
      "cases.link": "View case →",

      "process.eyebrow": "Process",
      "process.title": "How we work",
      "process.lead": "Clear stages from estimate to after-sales support.",
      "process.1.t": "Brief & estimate",
      "process.1.d": "We lock scope, deadlines, budget and technical constraints.",
      "process.2.t": "Design & engineering",
      "process.2.d": "Designers and technologists prepare a production-ready solution.",
      "process.3.t": "Production",
      "process.3.d": "Print, metalwork, coating and assembly in our own facilities.",
      "process.4.t": "Install & service",
      "process.4.d": "On-site installation and consulting after handover.",

      "numbers.eyebrow": "Scale",
      "numbers.title": "By the numbers",
      "numbers.lead": "A production company with regional presence across Uzbekistan.",
      "numbers.1": "projects per year",
      "numbers.2": "people on the team",
      "numbers.3": "years on the market",
      "numbers.4": "of production space",

      "advantages.eyebrow": "Advantages",
      "advantages.title": "Why choose GIGANT MEDIA",
      "advantages.lead": "In-house workshop, in-house design and ownership of results.",
      "advantages.1.chip": "Production",
      "advantages.1.t": "Own workshop",
      "advantages.1.d": "Better cost and shorter lead times without extra subcontractors.",
      "advantages.2.chip": "Expertise",
      "advantages.2.t": "Individual approach",
      "advantages.2.d": "A technologist helps optimize construction, budget and timing.",
      "advantages.3.chip": "Design",
      "advantages.3.t": "In-house design team",
      "advantages.3.d": "Professional layouts and visuals for any product line.",

      "reviews.eyebrow": "Reviews",
      "reviews.title": "Client feedback",
      "reviews.lead": "Quality, order speed and predictable pricing.",
      "reviews.1.chip": "Client",
      "reviews.1.q": "“Excellent quality and fast order handling. Fair prices. I will come back.”",
      "reviews.1.n": "Ramil Rinatovich",
      "reviews.1.r": "Company director",
      "reviews.2.chip": "Production",
      "reviews.2.q": "“Having an in-house workshop and design means fewer handoffs and faster install.”",
      "reviews.2.n": "B2B client",
      "reviews.2.r": "Retail / branding",
      "reviews.3.chip": "Service",
      "reviews.3.q": "“They keep consulting after handover — rare and valuable.”",
      "reviews.3.n": "Partner",
      "reviews.3.r": "Complex branding",

      "faq.eyebrow": "FAQ",
      "faq.title": "Frequently asked questions",
      "faq.lead": "Timelines, production and how to start a project.",
      "faq.1.q": "How long does a typical project take?",
      "faq.1.a": "From a few days for print/POSM to 2–4 weeks for complex branding — we lock timelines at estimate stage.",
      "faq.2.q": "Do you have in-house production?",
      "faq.2.a": "Yes. Own workshop, design team and install crews — quality, deadlines and cost under one roof.",
      "faq.3.q": "Do you work in the regions?",
      "faq.3.a": "Yes. Branches and projects across Uzbekistan: Tashkent, the region and key cities.",
      "faq.4.q": "How do I send a request?",
      "faq.4.a": "Use the form, call us or message on WhatsApp / Telegram — a manager will reply in business hours.",

      "contacts.eyebrow": "Contact",
      "contacts.title": "Get a consultation",
      "contacts.lead": "Leave your contacts — we will clarify scope, timing and budget.",
      "contacts.phone": "Phone",
      "contacts.more": "Also",
      "contacts.address": "Address",
      "contacts.addressValue": "Tashkent, Yunusabad district, 9th quarter, Yukori Karakamysh st., 5A",
      "contacts.quick": "Quick contact",
      "contacts.whatsapp": "WhatsApp",
      "contacts.telegram": "Telegram",
      "contacts.email": "Email",
      "form.name": "Name",
      "form.namePh": "How should we address you",
      "form.phone": "Phone",
      "form.phonePh": "+998 __ ___ __ __",
      "form.lang": "Preferred language",
      "form.langRu": "Russian",
      "form.langUz": "Uzbek",
      "form.langEn": "English",
      "form.msg": "Project brief",
      "form.msgPh": "Briefly: what you need and by when",
      "form.submit": "Send request",
      "form.note": "By submitting, you agree to personal data processing.",
      "form.errorName": "Please enter your name",
      "form.errorPhone": "Please enter a valid phone number",
      "form.success": "Request sent",
      "form.sending": "Sending…",

      "footer.tagline": "Full-cycle advertising and production company. Branches across Uzbekistan.",
      "footer.menu": "Menu",
      "footer.services": "Services",
      "footer.contacts": "Contacts",
      "footer.copy": "© GIGANT MEDIA",
      "footer.note": "Full-cycle advertising production · Uzbekistan",
      "lang.label": "Site language",
    },

    uz: {
      "nav.home": "Bosh sahifa",
      "nav.about": "Kompaniya",
      "nav.services": "Xizmatlar",
      "nav.cases": "Keyslar",
      "nav.advantages": "Afzalliklar",
      "nav.reviews": "Sharhlar",
      "nav.faq": "FAQ",
      "nav.contacts": "Aloqa",
      "nav.clients": "Mijozlar",
      "nav.cta": "Ariza qoldirish",
      "nav.menu": "Asosiy menyu",
      "nav.open": "Menyuni ochish",

      "hero.eyebrow": "Reklama ishlab chiqarish · O‘zbekiston",
      "hero.title": "Ishlaydigan reklamani ishlab chiqaramiz",
      "hero.lead":
        "GIGANT MEDIA — to‘liq tsikl: dizayn, ishlab chiqarish va montaj. Yorliqlar, POSM, bosma, mebel va obyektlarni bezash — butun O‘zbekiston bo‘ylab.",
      "hero.cta1": "Loyihani hisoblash",
      "hero.cta2": "Keyslarni ko‘rish",
      "hero.chip1": "Bozorda 15+ yil",
      "hero.chip2": "Yiliga 1500 loyiha",
      "hero.chip3": "O‘z ishlab chiqarish",
      "hero.float1": "85 mutaxassis",
      "hero.float2": "1500 m² maydon",
      "hero.imgAlt": "GIGANT MEDIA reklama ishlab chiqarish",

      "about.eyebrow": "Kompaniya",
      "about.title": "Biz haqimizda",
      "about.p1":
        "«GIGANT MEDIA» to‘liq tsikli reklama-ishlab chiqarish kompaniyasi 15 yildan ortiq reklama bozorida faoliyat yuritadi va yuqori sifatli reklama, matbaa va dizayn xizmatlarini taklif qiladi.",
      "about.p2":
        "Tashqi reklama ishlab chiqarishda boy tajribaga egamiz. Binolar, ofislar va do‘konlar fasadi mutaxassislarimiz tufayli yangicha ko‘rinishga ega. Filiallarimiz butun O‘zbekiston bo‘ylab ochilgan.",
      "about.geo": "Faoliyat geografiyasi",

      "services.eyebrow": "Xizmatlar",
      "services.title": "To‘liq tsiklning 13 yo‘nalishi",
      "services.lead": "Har bir xizmat — real ishlab chiqarish fotolari bilan aniq tijorat yechimi.",
      "services.more": "Batafsil →",
      "services.note": "Kafolat xizmati va maslahat — loyiha topshirilgandan keyin ham.",
      "services.prev": "Orqaga",
      "services.next": "Oldinga",
      "services.s1.t": "Yorliqlar",
      "services.s1.d": "Hajmli harflar, yorug‘lik qutilari va fasad konstruksiyalari montaj bilan.",
      "services.s1.b": "Kalit topshirish",
      "services.s2.t": "POSM",
      "services.s2.d": "Shelf-tokerlar, stopperlar, dispenserlar va savdo nuqtasi materiallari.",
      "services.s2.b": "SKU e’tibori",
      "services.s3.t": "Yo‘l bo‘yi reklama",
      "services.s3.d": "Transport yo‘llari bo‘ylab shildlar va konstruksiyalar.",
      "services.s3.b": "Maksimal qamrov",
      "services.s4.t": "Mebel",
      "services.s4.d": "Savdo va ko‘rgazma mebeli — brend va obyekt vazifasiga mos.",
      "services.s4.b": "Brendinga mos",
      "services.s5.t": "Vobblerlar",
      "services.s5.d": "Tokchadagi mahsulotga e’tiborni jalb qiluvchi POS elementlar.",
      "services.s5.b": "Tez urg‘u",
      "services.s6.t": "Mobil stendlar",
      "services.s6.d": "Aksiya, forum va chiqish tadbirlari uchun konstruksiyalar.",
      "services.s6.b": "Joyida yig‘ish",
      "services.s7.t": "Dekor",
      "services.s7.d": "Interer, vitrina va brend zonalar uchun dekorativ yechimlar.",
      "services.s7.b": "Muhit yaratish",
      "services.s8.t": "Kukunli bo‘yash",
      "services.s8.d": "Metall konstruksiya va reklama buyumlari uchun mustahkam qoplama.",
      "services.s8.b": "Uzoq muddat",
      "services.s9.t": "Kompleks bezash",
      "services.s9.d": "Obyektni bezashning to‘liq tsikli: konsepsiyadan montajgacha.",
      "services.s9.b": "Bitta pudratchi",
      "services.s10.t": "Reklama yopishtirish",
      "services.s10.d": "Transport, vitrina va sirtlarni plyonka bilan brendlash.",
      "services.s10.b": "Aniq rang",
      "services.s11.t": "Keng formatli bosma",
      "services.s11.d": "Bannerlar, brend zonalar, ichki va tashqi grafika.",
      "services.s11.b": "Bosma nazorati",
      "services.s12.t": "Suvenir va mukofotlar",
      "services.s12.d": "Korporativ sovg‘alar, mukofotlar va suvenir mahsulotlar.",
      "services.s12.b": "Brend imidji",
      "services.s13.t": "Ko‘rgazma stendlari",
      "services.s13.d": "Ko‘rgazma stendlari va konstruksiyalari kalit topshirish asosida.",
      "services.s13.b": "Namoyishga tayyor",

      "clients.eyebrow": "Mijozlar",
      "clients.title": "Bizga ishonishadi",
      "clients.lead": "Butun O‘zbekiston bo‘ylab reklama ishlab chiqaradigan brendlar.",

      "cases.eyebrow": "Keyslar",
      "cases.title": "Natija — oddiy galereya emas",
      "cases.lead": "Vazifa, yechim va o‘lchovli effekt — ishimizni shunday ko‘rsatamiz.",
      "cases.c1.client": "Riteyl",
      "cases.c1.title": "Savdo zonasini bezash",
      "cases.c1.d": "Kompleks brend zona: yorliq, navigatsiya va POSM yagona uslubda.",
      "cases.c1.m1": "14 kun",
      "cases.c1.m1l": "bajarish muddati",
      "cases.c1.m2": "1 pudratchi",
      "cases.c1.m2l": "dizayn → montaj",
      "cases.c2.client": "Bank",
      "cases.c2.title": "Fasad va kirish guruhi",
      "cases.c2.d": "Yorug‘lik konstruksiyalari va yopishtirish — rang va muddat nazorati bilan.",
      "cases.c3.client": "HoReCa",
      "cases.c3.title": "Interer grafikasi",
      "cases.c3.d": "Muassasa ishini to‘xtatmasdan dekor va bosma.",
      "cases.link": "Keysni ko‘rish →",

      "process.eyebrow": "Jarayon",
      "process.title": "Qanday ishlaymiz",
      "process.lead": "Hisob-kitobdan kafolat xizmatigacha shaffof bosqichlar.",
      "process.1.t": "Brif va hisob",
      "process.1.d": "Vazifa, muddat, byudjet va texnik cheklovlarni belgilaymiz.",
      "process.2.t": "Dizayn va muhandislik",
      "process.2.d": "Dizayn bo‘limi va texnolog ishlab chiqarishga tayyor yechim beradi.",
      "process.3.t": "Ishlab chiqarish",
      "process.3.d": "Bosma, metall, bo‘yoq va yig‘ish — o‘z maydonlarimizda.",
      "process.4.t": "Montaj va servis",
      "process.4.d": "Obyektda o‘rnatish va topshirishdan keyin maslahat.",

      "numbers.eyebrow": "Masshtab",
      "numbers.title": "Raqamlarda biz",
      "numbers.lead": "O‘zbekiston mintaqalarida mavjud ishlab chiqarish kompaniyasi.",
      "numbers.1": "yiliga loyihalar",
      "numbers.2": "jamiyatdagi xodimlar",
      "numbers.3": "reklama bozoridagi yillar",
      "numbers.4": "ishlab chiqarish maydoni",

      "advantages.eyebrow": "Afzalliklar",
      "advantages.title": "Nega GIGANT MEDIA",
      "advantages.lead": "O‘z sex, o‘z dizayn va natija uchun javobgarlik.",
      "advantages.1.chip": "Ishlab chiqarish",
      "advantages.1.t": "O‘z seximiz",
      "advantages.1.d": "Ortiqcha pudratchilarsiz optimal narx va qisqa muddat.",
      "advantages.2.chip": "Tajriba",
      "advantages.2.t": "Individual yondashuv",
      "advantages.2.d": "Texnolog konstruksiya, byudjet va muddatni optimallashtiradi.",
      "advantages.3.chip": "Dizayn",
      "advantages.3.t": "O‘z dizayn bo‘limi",
      "advantages.3.d": "Har qanday mahsulot uchun professional maketlar.",

      "reviews.eyebrow": "Sharhlar",
      "reviews.title": "Mijozlar fikri",
      "reviews.lead": "Sifat, buyurtmani qayta ishlash tezligi va bashoratli narx.",
      "reviews.1.chip": "Mijoz",
      "reviews.1.q": "«Ajoyib sifat, buyurtmani qayta ishlash tezligi yuqori. Qulay narxlar. Yana murojaat qilaman.»",
      "reviews.1.n": "Ramil Rinatovich",
      "reviews.1.r": "Kompaniya direktori",
      "reviews.2.chip": "Ishlab chiqarish",
      "reviews.2.q": "«O‘z sex va dizayn borligi muhim: kamroq kelishuv, tezroq montaj.»",
      "reviews.2.n": "B2B mijoz",
      "reviews.2.r": "Riteyl / bezash",
      "reviews.3.chip": "Xizmat",
      "reviews.3.q": "«Loyiha topshirilgandan keyin ham maslahat berishadi — bu kam uchraydi.»",
      "reviews.3.n": "Hamkor",
      "reviews.3.r": "Kompleks bezash",

      "faq.eyebrow": "FAQ",
      "faq.title": "Ko‘p so‘raladigan savollar",
      "faq.lead": "Muddatlar, ishlab chiqarish va loyihani qanday boshlash haqida.",
      "faq.1.q": "Oddiy loyiha qancha vaqt oladi?",
      "faq.1.a": "Bosma/POSM uchun bir necha kundan kompleks bezash uchun 2–4 haftagacha — muddatni hisob bosqichida belgilaymiz.",
      "faq.2.q": "O‘z ishlab chiqarishingiz bormi?",
      "faq.2.a": "Ha. O‘z sex, dizayn bo‘limi va montaj jamoasi — sifat, muddat va narx nazorati.",
      "faq.3.q": "Hududlarda ishlaysizmi?",
      "faq.3.a": "Ha. Filiallar va loyihalar butun O‘zbekiston bo‘ylab: Toshkent, viloyat va asosiy shaharlar.",
      "faq.4.q": "Arizani qanday qoldirish mumkin?",
      "faq.4.a": "Saytdagi forma, qo‘ng‘iroq yoki WhatsApp / Telegram — menejer ish vaqtida bog‘lanadi.",

      "contacts.eyebrow": "Aloqa",
      "contacts.title": "Maslahat olish",
      "contacts.lead": "Kontaktlaringizni qoldiring — vazifa, muddat va byudjetni aniqlaymiz.",
      "contacts.phone": "Telefon",
      "contacts.more": "Qo‘shimcha",
      "contacts.address": "Manzil",
      "contacts.addressValue": "Toshkent, Yunusobod tumani, 9-mavze, Yuqori Qoraqamish ko‘chasi, 5A",
      "contacts.quick": "Tezkor aloqa",
      "contacts.whatsapp": "WhatsApp",
      "contacts.telegram": "Telegram",
      "contacts.email": "Email",
      "form.name": "Ism",
      "form.namePh": "Sizni qanday deb chaqiraylik",
      "form.phone": "Telefon",
      "form.phonePh": "+998 __ ___ __ __",
      "form.lang": "Muloqot tili",
      "form.langRu": "Ruscha",
      "form.langUz": "O‘zbekcha",
      "form.langEn": "English",
      "form.msg": "Vazifa",
      "form.msgPh": "Qisqacha: nima kerak va qachongacha",
      "form.submit": "Ariza yuborish",
      "form.note": "Tugmani bosib, shaxsiy ma’lumotlarni qayta ishlashga rozilik bildirasiz.",
      "form.errorName": "Ismni kiriting",
      "form.errorPhone": "To‘g‘ri telefon raqamini kiriting",
      "form.success": "Ariza yuborildi",
      "form.sending": "Yuborilmoqda…",

      "footer.tagline": "To‘liq tsikli reklama-ishlab chiqarish kompaniyasi. Filiallar butun O‘zbekiston bo‘ylab.",
      "footer.menu": "Menyu",
      "footer.services": "Xizmatlar",
      "footer.contacts": "Aloqa",
      "footer.copy": "© GIGANT MEDIA",
      "footer.note": "To‘liq tsikli reklama ishlab chiqarish · O‘zbekiston",
      "lang.label": "Sayt tili",
    },
  },
};
