/* GIGANT MEDIA — multilingual content dictionary
   Default: Russian. Extend by adding keys to all locales. */
window.GM_CONTENT = {
  defaultLang: "ru",
  langs: ["ru", "en", "uz"],
  meta: {
    ru: {
      title: "GIGANT MEDIA — Рекламное производство полного цикла",
      description:
        "GIGANT MEDIA — рекламно-производственная компания полного цикла в Узбекистане: вывески, ПОСМ, печать, мебель, стенды. 15+ лет, своё производство, филиалы по стране.",
    },
    en: {
      title: "GIGANT MEDIA — Full-cycle advertising production",
      description:
        "GIGANT MEDIA is a full-cycle advertising and production company in Uzbekistan: signs, POSM, print, furniture, stands. 15+ years, in-house production, nationwide coverage.",
    },
    uz: {
      title: "GIGANT MEDIA — To‘liq tsikli reklama ishlab chiqarish",
      description:
        "GIGANT MEDIA — O‘zbekistondagi to‘liq tsikli reklama-ishlab chiqarish kompaniyasi: yorliqlar, POSM, bosma, mebel, stendlar. 15+ yil, o‘z ishlab chiqarish, butun mamlakat bo‘ylab filiallar.",
    },
  },
  dict: {
    ru: {
      "nav.home": "Главная",
      "nav.about": "О компании",
      "nav.services": "Услуги",
      "nav.cases": "Кейсы",
      "nav.advantages": "Преимущества",
      "nav.reviews": "Отзывы",
      "nav.faq": "FAQ",
      "nav.contacts": "Контакты",
      "nav.calc": "Калькулятор",
      "nav.production": "Производство",
      "services.allToggle": "Все услуги (13)",
      "contacts.mediaNote": "Свой цех: печать, сборка и контроль перед монтажом.",
      "audience.eyebrow": "Для кого",
      "audience.title": "Решаем задачи бизнеса",
      "audience.lead": "Четыре типичных запроса — от точки продаж до сетевого объекта.",
      "audience.1.chip": "Ритейл",
      "audience.1.t": "Единый стиль торговой зоны",
      "audience.1.d": "Вывеска, навигация и POSM без разных подрядчиков и расхождения цвета.",
      "audience.2.chip": "Банки / офисы",
      "audience.2.t": "Фасад и входная группа в срок",
      "audience.2.d": "Световые конструкции и оклейка с контролем бренда и графика монтажа.",
      "audience.3.chip": "HoReCa",
      "audience.3.t": "Интерьер без простоя зала",
      "audience.3.d": "Графика и декор с ночным монтажом — заведение продолжает работать.",
      "audience.4.chip": "Маркетинг",
      "audience.4.t": "Срочный тираж и акции",
      "audience.4.d": "Печать, POSM и мобильные конструкции под дату запуска кампании.",
      "nav.clients": "Клиенты",
      "nav.cta": "Получить расчёт",
      "nav.menu": "Основное меню",
      "nav.open": "Открыть меню",

      "hero.eyebrow": "Рекламное производство · Узбекистан",
      "hero.title": "Вывески, POSM и оформление объектов — без срыва сроков",
      "hero.lead": "Свой цех, дизайн и монтаж в одном договоре. Ответ по задаче обычно до 4 часов в рабочий день — ведём проект до сдачи по регионам Узбекистана.",
      "hero.cta1": "Получить расчёт",
      "hero.seg1": "Для ритейла",
      "hero.seg2": "Для банков",
      "hero.seg3": "Для HoReCa",
      "hero.cta2": "Смотреть кейсы",
      "hero.chip1": "15+ лет на рынке",
      "hero.chip2": "1500 проектов / год",
      "hero.chip3": "Собственное производство",
      "hero.float1": "85 специалистов",
      "hero.float2": "1500 м² площадей",
      "hero.imgAlt": "Производство рекламной продукции GIGANT MEDIA",

      "about.eyebrow": "Компания",
      "about.title": "О компании",
      "about.p1":
        "GIGANT MEDIA — рекламное производство полного цикла. 15+ лет: дизайн, свой цех и монтаж по Узбекистану.",
      "about.p2":
        "За плечами — богатый опыт производства наружной рекламы. Многие фасады зданий, офисов и магазинов выглядят по-новому благодаря нашим специалистам. Филиалы открыты по всему Узбекистану.",
      "about.geo": "География присутствия",
      "mosaic.eyebrow": "Производство",
      "mosaic.title": "Превосходство через контроль качества",
      "mosaic.1.t": "Свой цех и инженерия",
      "mosaic.1.d": "Печать, металлоконструкции и сборка на своих площадях — без лишней цепочки подрядчиков.",
      "mosaic.2.t": "Приёмка на каждом этапе",
      "mosaic.2.d": "Макет, цветопроба, производство и монтаж — фиксируем качество до сдачи объекта.",
      "mosaic.3.t": "От макета до монтажа",
      "mosaic.more": "Читать полностью",
      "mosaic.cta": "Узнать больше",
      "download.eyebrow": "Материалы",
      "download.title": "Получить презентацию и примеры работ",
      "download.lead": "Оставьте контакты — пришлём подборку кейсов и ориентиры по срокам под вашу задачу.",
      "download.cta": "Запросить материалы",
      "download.wa": "Написать в WhatsApp",
      "fab.call": "Позвонить",

      "services.eyebrow": "Услуги",
      "services.title": "Ключевые направления",
      "services.lead": "Шесть якорных услуг полного цикла. Остальные направления — по запросу.",
      "services.more": "Подробнее →",
      "services.ask": "Запросить расчёт →",
      "services.moreLabel": "Ещё направления",
      "services.moreCta": "Запросить по направлению",
      "services.note": "Гарантийное обслуживание и консультации — даже после сдачи проекта.",
      "services.prev": "Назад",
      "services.next": "Вперёд",
      "services.s1.t": "Вывески",
      "services.s1.d": "Объёмные буквы, световые короба и фасадные конструкции с монтажом.",
      "services.s1.b": "Монтаж под ключ",
      "services.s2.t": "ПОСМ",
      "services.s2.d": "Шелфтокеры, стопперы, диспенсеры и материалы для точки продаж.",
      "services.s2.b": "Рост внимания к SKU",
      "services.s3.t": "Придорожная реклама",
      "services.s3.d": "Щиты, конструкции и носители вдоль транспортных артерий.",
      "services.s3.b": "Максимальный охват",
      "services.s4.t": "Мебель",
      "services.s4.d": "Торговая и выставочная мебель под бренд и задачу объекта.",
      "services.s4.b": "Под ваш бренд",
      "services.s5.t": "Воблеры",
      "services.s5.d": "POS-элементы, которые привлекают внимание к товару на полке.",
      "services.s5.b": "Быстрый акцент",
      "services.s6.t": "Мобильные стенды",
      "services.s6.d": "Конструкции для акций, форумов и выездных мероприятий.",
      "services.s6.b": "Сборка на месте",
      "services.s7.t": "Декор",
      "services.s7.d": "Декоративные решения для интерьеров, витрин и бренд-зон.",
      "services.s7.b": "Атмосфера объекта",
      "services.s8.t": "Порошковая покраска",
      "services.s8.d": "Стойкое покрытие металлоконструкций и рекламных изделий.",
      "services.s8.b": "Долговечность",
      "services.s9.t": "Комплексное оформление",
      "services.s9.d": "Полный цикл оформления объекта: от концепции до монтажа.",
      "services.s9.b": "Один подрядчик",
      "services.s10.t": "Рекламная оклейка",
      "services.s10.d": "Брендирование транспорта, витрин и поверхностей плёнкой.",
      "services.s10.b": "Точный цвет",
      "services.s11.t": "Широкоформатная печать",
      "services.s11.d": "Баннеры, бренд-зоны, интерьерная и наружная графика.",
      "services.s11.b": "Контроль печати",
      "services.s12.t": "Сувениры и награды",
      "services.s12.d": "Корпоративные подарки, награды и сувенирная продукция.",
      "services.s12.b": "Имидж бренда",
      "services.s13.t": "Выставочные стенды",
      "services.s13.d": "Выставочные стенды и конструкции под ключ.",
      "services.s13.b": "Готово к показу",

      "clients.eyebrow": "Клиенты",
      "clients.title": "Нам доверяют",
      "clients.lead": "Бренды и компании, для которых мы производим рекламу по всему Узбекистану.",

      "cases.eyebrow": "Кейсы",
      "cases.title": "Результаты вместо сухого портфолио",
      "cases.lead": "Задача, решение и измеримый эффект — так мы показываем работу.",
      "cases.c1.client": "Федеральная розничная сеть",
      "cases.c1.title": "Бренд-зона под ключ за 14 дней",
      "cases.c1.d": "Вывеска, навигация и POSM в одном стиле — без цепочки субподрядчиков.",
      "cases.c1.m1": "14 дней",
      "cases.c1.m1l": "срок реализации",
      "cases.c1.m2": "1 подрядчик",
      "cases.c1.m2l": "дизайн → монтаж",
      "cases.c2.client": "Банк · сеть отделений",
      "cases.c2.title": "Фасад с контролем цвета бренда",
      "cases.c2.d": "Световые конструкции и оклейка: макет → производство → монтаж за 21 день.",
      "cases.c2.m1": "21 день",
      "cases.c2.m1l": "от макета до монтажа",
      "cases.c2.m2": "±ΔE 2",
      "cases.c2.m2l": "контроль цвета бренда",
      "cases.c3.client": "Региональная сеть кафе",
      "cases.c3.title": "Интерьер без остановки зала",
      "cases.c3.d": "Ночной монтаж графики в 3 зонах — зал работал на следующий день.",
      "cases.c3.m1": "Ночной монтаж",
      "cases.c3.m1l": "без простоя зала",
      "cases.c3.m2": "3 зоны",
      "cases.c3.m2l": "единый визуальный код",
      "cases.link": "Смотреть кейс →",
      "cases.ask": "Получить похожий расчёт →",

      "team.eyebrow": "Команда",
      "team.title": "Наши специалисты",
      "team.lead": "Фото и профили сотрудников появятся здесь — блок готов к наполнению.",
      "team.slotName": "Имя Фамилия",
      "team.slotRole": "Должность",

      "process.eyebrow": "Процесс",
      "process.title": "Как мы работаем",
      "process.lead": "Прозрачные этапы: от расчёта до гарантийного сопровождения.",
      "process.1.t": "Бриф и расчёт",
      "process.1.d": "Фиксируем задачу, сроки, бюджет и технические ограничения.",
      "process.2.t": "Дизайн и инженерия",
      "process.2.d": "Дизайн-отдел и технолог готовят решение под производство.",
      "process.3.t": "Производство",
      "process.3.d": "Печать, металлоконструкции, покраска и сборка на своих площадях.",
      "process.4.t": "Монтаж и сервис",
      "process.4.d": "Установка на объекте и консультации после сдачи проекта.",

      "numbers.eyebrow": "Масштаб",
      "numbers.title": "О нас в цифрах",
      "numbers.lead": "Производственная компания с присутствием по регионам Узбекистана.",
      "numbers.1": "проектов в год",
      "numbers.2": "сотрудников в команде",
      "numbers.3": "лет на рекламном рынке",
      "numbers.4": "производственных площадей",

      "advantages.eyebrow": "Преимущества",
      "advantages.title": "Почему выбирают GIGANT MEDIA",
      "advantages.lead": "Свой цех, свой дизайн и ответственность за результат.",
      "advantages.1.chip": "Производство",
      "advantages.1.t": "Собственный цех",
      "advantages.1.d": "Оптимальная стоимость и сжатые сроки без лишних подрядных звеньев.",
      "advantages.2.chip": "Экспертиза",
      "advantages.2.t": "Индивидуальный подход",
      "advantages.2.d": "Технолог помогает оптимизировать конструкцию, бюджет и сроки.",
      "advantages.3.chip": "Дизайн",
      "advantages.3.t": "Свой дизайн-отдел",
      "advantages.3.d": "Профессиональные макеты и визуалы под любую продукцию.",

      "reviews.eyebrow": "Отзывы",
      "reviews.title": "Слова клиентов",
      "reviews.lead": "Качество, скорость обработки заказа и предсказуемая цена.",
      "reviews.1.chip": "Ритейл",
      "reviews.1.q": "«Отличное качество, скорость обработки заказа на высоте. Приемлемые цены. Обязательно обращусь снова.»",
      "reviews.1.n": "Рамиль Ринатович",
      "reviews.1.r": "Директор · торговая сеть",
      "reviews.2.chip": "Закупки",
      "reviews.2.q": "«Важно, что есть свой цех и дизайн: меньше согласований, быстрее выход на монтаж.»",
      "reviews.2.n": "Азиз К.",
      "reviews.2.r": "Руководитель закупок · ритейл-сеть",
      "reviews.3.chip": "HoReCa",
      "reviews.3.q": "«После сдачи проекта продолжают консультировать — это редкость и сильный аргумент.»",
      "reviews.3.n": "Нигора М.",
      "reviews.3.r": "Бренд-менеджер · сеть кафе",

      "faq.eyebrow": "FAQ",
      "faq.title": "Частые вопросы",
      "faq.lead": "Коротко о сроках, производстве и том, как стартовать проект.",
      "faq.1.q": "Сколько занимает типовой проект?",
      "faq.1.a": "От нескольких дней для печати и POSM до 2–4 недель для комплексного оформления — сроки фиксируем на этапе расчёта.",
      "faq.2.q": "У вас своё производство?",
      "faq.2.a": "Да. Собственный цех, дизайн-отдел и монтажные бригады — это контроль качества, сроков и стоимости.",
      "faq.3.q": "Работаете ли вы в регионах?",
      "faq.3.a": "Да. Филиалы и проекты по всему Узбекистану: Ташкент, область и ключевые города.",
      "faq.4.q": "Что нужно для точного расчёта?",
      "faq.4.a": "Фото объекта, адрес, примерные размеры, желаемый формат и референс (если есть). Остальное уточним на созвоне.",
      "faq.5.q": "Делаете ли дизайн с нуля?",
      "faq.5.a": "Да. Готовим концепцию, макеты и технические файлы под производство — или адаптируем ваш брендбук.",
      "faq.6.q": "Помогаете ли с согласованием наружной рекламы?",
      "faq.6.a": "Подготовим эскиз и технические данные под согласование. Требования зависят от объекта, фасада и типа конструкции — уточняем до старта.",
      "faq.7.q": "Можно ли срочный заказ?",
      "faq.7.a": "Да, при наличии слотов в производстве. Срочность согласуем на старте и зафиксируем в плане работ.",
      "faq.8.q": "Какая гарантия на изделия?",
      "faq.8.a": "Гарантия по договору после сдачи. Контроль на этапах: макет, цветопроба, производство и приёмка монтажа.",
      "faq.9.q": "Можно ли заказать только производство без монтажа?",
      "faq.9.a": "Да. Работаем полным циклом или отдельными этапами: дизайн, производство, монтаж, замена элементов.",
      "faq.10.q": "Сколько ждать ответа на заявку?",
      "faq.10.a": "В рабочее время обычно отвечаем в течение 4 часов. Ночью и в выходные — в ближайший рабочий день.",
      "trust.1": "Ответ в рабочий день · обычно до 4 часов",
      "trust.2": "Договор и гарантия по договору",
      "trust.3": "Выезд / замер по согласованию",
      "trust.4": "Монтаж по регионам Узбекистана",
      "workshop.eyebrow": "Цех",
      "workshop.title": "Своё производство — не субподряд",
      "workshop.lead": "Печать, металлоконструкции, покраска и сборка на своих площадях.",
      "workshop.c1": "Производственная линия",
      "workshop.c2": "Сборка и контроль",
      "workshop.c3": "Готовые конструкции",
      "workshop.c4": "Покраска и финиш",
      "workshop.c5": "Объекты после монтажа",
      "workshop.c6": "Вывески и фасады",
      "seo.lb.t": "Световые короба",
      "seo.lb.d": "LED-короба и световые конструкции для фасада и интерьера с монтажом.",
      "seo.lb.b": "Яркость и срок службы",

      "contacts.eyebrow": "Контакты",
      "contacts.title": "Получить расчёт",
      "contacts.lead": "Оставьте контакты — уточним задачу и пришлём сроки с бюджетом в рабочее время.",
      "contacts.trust1": "Ответ в рабочий день · обычно до 4 часов",
      "contacts.trust2": "Договор · гарантия и консультации после сдачи",
      "contacts.trust3": "Один подрядчик: дизайн → производство → монтаж",
      "contacts.phone": "Телефон",
      "contacts.more": "Дополнительно",
      "contacts.address": "Адрес",
      "contacts.addressValue": "г. Ташкент, Юнусабадский район, 9 квартал, ул. Юкори Каракамыш, 5А",
      "contacts.quick": "Быстрая связь",
      "contacts.whatsapp": "WhatsApp",
      "contacts.telegram": "Telegram",
      "contacts.email": "Email",
      "form.name": "Имя",
      "form.namePh": "Как к вам обращаться",
      "form.phone": "Телефон",
      "form.phonePh": "+998 __ ___ __ __",
      "form.lang": "Язык общения",
      "form.langRu": "Русский",
      "form.langUz": "Узбекский",
      "form.langEn": "English",
      "form.msg": "Задача",
      "form.msgPh": "Коротко: объект, объём, город",
      "form.submit": "Получить расчёт",
      "form.task": "Тип задачи",
      "form.taskPh": "Выберите направление",
      "form.taskSigns": "Вывески",
      "form.taskPosm": "POSM / печать",
      "form.taskComplex": "Комплексное оформление",
      "form.taskOther": "Другое",
      "form.deadline": "Желаемый срок",
      "form.deadlinePh": "Например: до 15 августа",
      "form.errorTask": "Выберите тип задачи",
      "form.successWa": "Написать в WhatsApp",
      "form.successCall": "Позвонить",
      "form.note": "Нажимая кнопку, вы соглашаетесь на обработку данных. Перезвоним в рабочее время.",
      "form.errorName": "Укажите имя",
      "form.errorPhone": "Укажите корректный телефон",
      "form.success": "Заявка принята. Можете сразу написать в WhatsApp или позвонить — так быстрее.",
      "midCta.1.eyebrow": "Следующий шаг",
      "midCta.1.title": "Нужен похожий результат?",
      "midCta.1.lead": "Опишите задачу — пришлём расчёт и сроки в течение рабочего дня.",
      "midCta.1.cta": "Получить расчёт",
      "midCta.2.eyebrow": "Без риска",
      "midCta.2.title": "Один подрядчик — от макета до монтажа",
      "midCta.2.lead": "Свой цех, свой дизайн и сопровождение после сдачи. Перезвоним в рабочее время.",
      "sticky.cta": "Расчёт",
      "sticky.wa": "WhatsApp",
      "form.sending": "Отправляем…",

      "footer.tagline": "Рекламно-производственная компания полного цикла. Филиалы по всему Узбекистану.",
      "footer.menu": "Меню",
      "footer.services": "Услуги",
      "footer.contacts": "Контакты",
      "footer.copy": "© GIGANT MEDIA",
      "footer.note": "Full-cycle advertising production · Uzbekistan",
      "footer.dev": "Разработка и продвижение сайта — <a href=\"https://t.me/webgiants\" target=\"_blank\" rel=\"noopener noreferrer\">t.me/webgiants</a>",

      "calc.skip": "К калькулятору",
      "calc.eyebrow": "Расчёт стоимости",
      "calc.title": "Калькулятор стоимости",
      "calc.lead": "Официальный расчёт стоимости рекламной продукции. Выберите тип изделия и параметры. Итоговая цена обновляется автоматически.",
      "calc.home": "На главную",
      "calc.footer": "GIGANT MEDIA · Калькулятор стоимости",
      "lang.label": "Язык сайта",
    },

    en: {
      "nav.home": "Home",
      "nav.about": "About",
      "nav.services": "Services",
      "nav.cases": "Cases",
      "nav.advantages": "Advantages",
      "nav.reviews": "Reviews",
      "nav.faq": "FAQ",
      "nav.contacts": "Contact",
      "nav.calc": "Calculator",
      "nav.production": "Production",
      "services.allToggle": "All services (13)",
      "contacts.mediaNote": "Own workshop: print, assembly and checks before install.",
      "audience.eyebrow": "Who it’s for",
      "audience.title": "Built for business tasks",
      "audience.lead": "Four typical briefs — from a single store to a network rollout.",
      "audience.1.chip": "Retail",
      "audience.1.t": "One look for the sales floor",
      "audience.1.d": "Signage, wayfinding and POSM without vendor chains or color drift.",
      "audience.2.chip": "Banks / offices",
      "audience.2.t": "Facade and entrance on schedule",
      "audience.2.d": "Lightboxes and wrapping with brand control and install timing.",
      "audience.3.chip": "HoReCa",
      "audience.3.t": "Interiors without downtime",
      "audience.3.d": "Graphics and decor with night install — the venue keeps working.",
      "audience.4.chip": "Marketing",
      "audience.4.t": "Rush print and campaigns",
      "audience.4.d": "Print, POSM and mobile structures timed to launch day.",
      "nav.clients": "Clients",
      "nav.cta": "Get an estimate",
      "nav.menu": "Main menu",
      "nav.open": "Open menu",

      "hero.eyebrow": "Advertising production · Uzbekistan",
      "hero.title": "Signs, POSM and object branding — without missed deadlines",
      "hero.lead": "Own workshop, design and install in one contract. Usually reply within 4 business hours — deliver across Uzbekistan.",
      "hero.cta1": "Get an estimate",
      "hero.seg1": "For retail",
      "hero.seg2": "For banks",
      "hero.seg3": "For HoReCa",
      "hero.cta2": "View cases",
      "hero.chip1": "15+ years on the market",
      "hero.chip2": "1,500 projects / year",
      "hero.chip3": "In-house production",
      "hero.float1": "85 specialists",
      "hero.float2": "1,500 m² facilities",
      "hero.imgAlt": "GIGANT MEDIA advertising production",

      "about.eyebrow": "Company",
      "about.title": "About us",
      "about.p1":
        "GIGANT MEDIA is full-cycle advertising production. 15+ years: design, own workshop and install across Uzbekistan.",
      "about.p2":
        "We have deep experience in outdoor advertising. Facades of offices and stores look new thanks to our team. Branches are open across Uzbekistan.",
      "about.geo": "Coverage geography",
      "mosaic.eyebrow": "Production",
      "mosaic.title": "Excellence through quality control",
      "mosaic.1.t": "Own workshop and engineering",
      "mosaic.1.d": "Print, metalwork and assembly on our floors — without an extra contractor chain.",
      "mosaic.2.t": "Checks at every stage",
      "mosaic.2.d": "Artwork, color proof, production and install — quality locked before handover.",
      "mosaic.3.t": "From artwork to install",
      "mosaic.more": "Read more",
      "mosaic.cta": "Learn more",
      "download.eyebrow": "Materials",
      "download.title": "Get a presentation and work samples",
      "download.lead": "Leave your contacts — we will send a case selection and timing for your brief.",
      "download.cta": "Request materials",
      "download.wa": "Message on WhatsApp",
      "fab.call": "Call",

      "services.eyebrow": "Services",
      "services.title": "Key directions",
      "services.lead": "Six core full-cycle services. More directions available on request.",
      "services.more": "Learn more →",
      "services.ask": "Request an estimate →",
      "services.moreLabel": "More directions",
      "services.moreCta": "Request by direction",
      "services.note": "Warranty support and consulting — even after project handover.",
      "services.prev": "Previous",
      "services.next": "Next",
      "services.s1.t": "Signs",
      "services.s1.d": "Dimensional letters, lightboxes and facade structures with installation.",
      "services.s1.b": "Turnkey install",
      "services.s2.t": "POSM",
      "services.s2.d": "Shelf talkers, stoppers, dispensers and in-store materials.",
      "services.s2.b": "SKU attention",
      "services.s3.t": "Roadside ads",
      "services.s3.d": "Boards and structures along major traffic routes.",
      "services.s3.b": "Maximum reach",
      "services.s4.t": "Furniture",
      "services.s4.d": "Retail and exhibition furniture tailored to brand and space.",
      "services.s4.b": "Brand-fit build",
      "services.s5.t": "Wobblers",
      "services.s5.d": "POS elements that pull attention to products on the shelf.",
      "services.s5.b": "Fast highlight",
      "services.s6.t": "Mobile stands",
      "services.s6.d": "Structures for promotions, forums and field events.",
      "services.s6.b": "On-site setup",
      "services.s7.t": "Decor",
      "services.s7.d": "Decorative solutions for interiors, windows and brand zones.",
      "services.s7.b": "Space atmosphere",
      "services.s8.t": "Powder coating",
      "services.s8.d": "Durable coating for metal structures and advertising products.",
      "services.s8.b": "Long lifespan",
      "services.s9.t": "Complex branding",
      "services.s9.d": "Full object branding cycle: from concept to installation.",
      "services.s9.b": "One contractor",
      "services.s10.t": "Wrapping",
      "services.s10.d": "Vehicle, window and surface branding with vinyl.",
      "services.s10.b": "Color accuracy",
      "services.s11.t": "Wide-format print",
      "services.s11.d": "Banners, brand zones, indoor and outdoor graphics.",
      "services.s11.b": "Print control",
      "services.s12.t": "Souvenirs & awards",
      "services.s12.d": "Corporate gifts, awards and souvenir products.",
      "services.s12.b": "Brand image",
      "services.s13.t": "Exhibition stands",
      "services.s13.d": "Exhibition stands and structures delivered turnkey.",
      "services.s13.b": "Show-ready",

      "clients.eyebrow": "Clients",
      "clients.title": "Trusted by brands",
      "clients.lead": "Companies we produce advertising for across Uzbekistan.",

      "cases.eyebrow": "Cases",
      "cases.title": "Results instead of a flat gallery",
      "cases.lead": "Challenge, solution and measurable outcome — how we present work.",
      "cases.c1.client": "Store chain · retail",
      "cases.c1.title": "Turnkey brand zone in 14 days",
      "cases.c1.d": "Full brand zone: signage, navigation and POSM in one system.",
      "cases.c1.m1": "14 days",
      "cases.c1.m1l": "delivery time",
      "cases.c1.m2": "1 contractor",
      "cases.c1.m2l": "design → install",
      "cases.c2.client": "Bank · entrance group",
      "cases.c2.title": "Facade with brand color control",
      "cases.c2.d": "Light structures and wrapping with color and deadline control.",
      "cases.c2.m1": "21 days",
      "cases.c2.m1l": "from artwork to install",
      "cases.c2.m2": "±ΔE 2",
      "cases.c2.m2l": "brand color control",
      "cases.c3.client": "Cafe chain · HoReCa",
      "cases.c3.title": "Interiors without hall downtime",
      "cases.c3.d": "Decor and print that keep the venue running during works.",
      "cases.c3.m1": "Night install",
      "cases.c3.m1l": "no venue downtime",
      "cases.c3.m2": "3 zones",
      "cases.c3.m2l": "one visual system",
      "cases.link": "View case →",
      "cases.ask": "Get a similar estimate →",

      "team.eyebrow": "Team",
      "team.title": "Our specialists",
      "team.lead": "Photos and profiles will appear here — the block is ready to fill.",
      "team.slotName": "Full name",
      "team.slotRole": "Role",

      "process.eyebrow": "Process",
      "process.title": "How we work",
      "process.lead": "Clear stages from estimate to after-sales support.",
      "process.1.t": "Brief & estimate",
      "process.1.d": "We lock scope, deadlines, budget and technical constraints.",
      "process.2.t": "Design & engineering",
      "process.2.d": "Designers and technologists prepare a production-ready solution.",
      "process.3.t": "Production",
      "process.3.d": "Print, metalwork, coating and assembly in our own facilities.",
      "process.4.t": "Install & service",
      "process.4.d": "On-site installation and consulting after handover.",

      "numbers.eyebrow": "Scale",
      "numbers.title": "By the numbers",
      "numbers.lead": "A production company with regional presence across Uzbekistan.",
      "numbers.1": "projects per year",
      "numbers.2": "people on the team",
      "numbers.3": "years on the market",
      "numbers.4": "of production space",

      "advantages.eyebrow": "Advantages",
      "advantages.title": "Why choose GIGANT MEDIA",
      "advantages.lead": "In-house workshop, in-house design and ownership of results.",
      "advantages.1.chip": "Production",
      "advantages.1.t": "Own workshop",
      "advantages.1.d": "Better cost and shorter lead times without extra subcontractors.",
      "advantages.2.chip": "Expertise",
      "advantages.2.t": "Individual approach",
      "advantages.2.d": "A technologist helps optimize construction, budget and timing.",
      "advantages.3.chip": "Design",
      "advantages.3.t": "In-house design team",
      "advantages.3.d": "Professional layouts and visuals for any product line.",

      "reviews.eyebrow": "Reviews",
      "reviews.title": "Client feedback",
      "reviews.lead": "Quality, order speed and predictable pricing.",
      "reviews.1.chip": "Client",
      "reviews.1.q": "“Excellent quality and fast order handling. Fair prices. I will come back.”",
      "reviews.1.n": "Ramil Rinatovich",
      "reviews.1.r": "Company director",
      "reviews.2.chip": "Production",
      "reviews.2.q": "“Having an in-house workshop and design means fewer handoffs and faster install.”",
      "reviews.2.n": "Aziz K.",
      "reviews.2.r": "Procurement lead, retail",
      "reviews.3.chip": "Service",
      "reviews.3.q": "“They keep consulting after handover — rare and valuable.”",
      "reviews.3.n": "Nigora M.",
      "reviews.3.r": "Brand manager, cafe chain",

      "faq.eyebrow": "FAQ",
      "faq.title": "Frequently asked questions",
      "faq.lead": "Timelines, production and how to start a project.",
      "faq.1.q": "How long does a typical project take?",
      "faq.1.a": "From a few days for print/POSM to 2–4 weeks for complex branding — we lock timelines at estimate stage.",
      "faq.2.q": "Do you have in-house production?",
      "faq.2.a": "Yes. Own workshop, design team and install crews — quality, deadlines and cost under one roof.",
      "faq.3.q": "Do you work in the regions?",
      "faq.3.a": "Yes. Branches and projects across Uzbekistan: Tashkent, the region and key cities.",
      "faq.4.q": "What do you need for an accurate estimate?",
      "faq.4.a": "Object photo, address, approx. sizes, desired format and a reference if you have one. We clarify the rest on a call.",
      "faq.5.q": "Do you design from scratch?",
      "faq.5.a": "Yes. Concept, artwork and production-ready files — or we adapt your brand guidelines.",
      "faq.6.q": "Do you help with outdoor advertising permits?",
      "faq.6.a": "We prepare artwork and technical specs for approval. Requirements depend on the site, facade and structure type — we clarify before start.",
      "faq.7.q": "Can you handle rush jobs?",
      "faq.7.a": "Yes, when production slots are available. We confirm urgency upfront and lock it into the plan.",
      "faq.8.q": "What warranty do products include?",
      "faq.8.a": "Warranty per contract after handover. Checks at artwork, color proof, production and install stages.",
      "faq.9.q": "Can I order production without installation?",
      "faq.9.a": "Yes. Full cycle or separate stages: design, production, install, part replacement.",
      "faq.10.q": "How fast do you reply to a request?",
      "faq.10.a": "In business hours we usually reply within 4 hours. Nights and weekends — next business day.",
      "trust.1": "Business-day reply · usually within 4 hours",
      "trust.2": "Contract and warranty by agreement",
      "trust.3": "Site visit / measure by arrangement",
      "trust.4": "Install across Uzbekistan regions",
      "workshop.eyebrow": "Workshop",
      "workshop.title": "Own production — not subcontractors",
      "workshop.lead": "Print, metalwork, coating and assembly on our floors.",
      "workshop.c1": "Production line",
      "workshop.c2": "Assembly and QC",
      "workshop.c3": "Finished structures",
      "workshop.c4": "Coating and finish",
      "workshop.c5": "Installed objects",
      "workshop.c6": "Signs and facades",
      "seo.lb.t": "Lightboxes",
      "seo.lb.d": "LED lightboxes and illuminated structures for facade and interiors with install.",
      "seo.lb.b": "Brightness and lifespan",

      "contacts.eyebrow": "Contact",
      "contacts.title": "Get an estimate",
      "contacts.lead": "Leave your contacts — we clarify the brief and send timing with budget in business hours.",
      "contacts.trust1": "Reply in business hours · usually within 4 hours",
      "contacts.trust2": "Contract · warranty and consulting after handover",
      "contacts.trust3": "One contractor: design → production → install",
      "contacts.phone": "Phone",
      "contacts.more": "Also",
      "contacts.address": "Address",
      "contacts.addressValue": "Tashkent, Yunusabad district, 9th quarter, Yukori Karakamysh st., 5A",
      "contacts.quick": "Quick contact",
      "contacts.whatsapp": "WhatsApp",
      "contacts.telegram": "Telegram",
      "contacts.email": "Email",
      "form.name": "Name",
      "form.namePh": "How should we address you",
      "form.phone": "Phone",
      "form.phonePh": "+998 __ ___ __ __",
      "form.lang": "Preferred language",
      "form.langRu": "Russian",
      "form.langUz": "Uzbek",
      "form.langEn": "English",
      "form.msg": "Project brief",
      "form.msgPh": "Briefly: site, scope, city",
      "form.submit": "Get an estimate",
      "form.task": "Task type",
      "form.taskPh": "Choose a direction",
      "form.taskSigns": "Signs",
      "form.taskPosm": "POSM / print",
      "form.taskComplex": "Complex branding",
      "form.taskOther": "Other",
      "form.deadline": "Desired deadline",
      "form.deadlinePh": "E.g. by August 15",
      "form.errorTask": "Choose a task type",
      "form.successWa": "Message on WhatsApp",
      "form.successCall": "Call",
      "form.note": "By submitting you agree to data processing. We call back in business hours.",
      "form.errorName": "Please enter your name",
      "form.errorPhone": "Please enter a valid phone number",
      "form.success": "Request received. Message us on WhatsApp or call — it’s faster.",
      "midCta.1.eyebrow": "Next step",
      "midCta.1.title": "Need a similar result?",
      "midCta.1.lead": "Describe the brief — we send estimate and timing within a business day.",
      "midCta.1.cta": "Get an estimate",
      "midCta.2.eyebrow": "Low risk",
      "midCta.2.title": "One contractor — from artwork to install",
      "midCta.2.lead": "Own workshop, in-house design and post-handover support. We call back in business hours.",
      "sticky.cta": "Estimate",
      "sticky.wa": "WhatsApp",
      "form.sending": "Sending…",

      "footer.tagline": "Full-cycle advertising and production company. Branches across Uzbekistan.",
      "footer.menu": "Menu",
      "footer.services": "Services",
      "footer.contacts": "Contacts",
      "footer.copy": "© GIGANT MEDIA",
      "footer.note": "Full-cycle advertising production · Uzbekistan",
      "footer.dev": "Website development &amp; promotion — <a href=\"https://t.me/webgiants\" target=\"_blank\" rel=\"noopener noreferrer\">t.me/webgiants</a>",

      "calc.skip": "To calculator",
      "calc.eyebrow": "Cost estimate",
      "calc.title": "Cost calculator",
      "calc.lead": "Official cost calculator for advertising products. Select the product type and parameters. The total updates automatically.",
      "calc.home": "Back to home",
      "calc.footer": "GIGANT MEDIA · Cost calculator",
      "lang.label": "Site language",
    },

    uz: {
      "nav.home": "Bosh sahifa",
      "nav.about": "Kompaniya",
      "nav.services": "Xizmatlar",
      "nav.cases": "Keyslar",
      "nav.advantages": "Afzalliklar",
      "nav.reviews": "Sharhlar",
      "nav.faq": "FAQ",
      "nav.calc": "Kalkulyator",
      "nav.contacts": "Aloqa",
      "nav.production": "Ishlab chiqarish",
      "services.allToggle": "Barcha xizmatlar (13)",
      "contacts.mediaNote": "O‘z sex: bosma, yig‘ish va montaj oldidan nazorat.",
      "audience.eyebrow": "Kim uchun",
      "audience.title": "Biznes vazifalarini yechamiz",
      "audience.lead": "To‘rt tipik so‘rov — savdo nuqtasidan tarmoq obyektigacha.",
      "audience.1.chip": "Riteyl",
      "audience.1.t": "Savdo zonasida yagona uslub",
      "audience.1.d": "Yorliq, navigatsiya va POSM — turli pudratchilarsiz va rang farqisiz.",
      "audience.2.chip": "Bank / ofis",
      "audience.2.t": "Fasad va kirish guruhi muddatida",
      "audience.2.d": "Yorug‘lik konstruksiyalari va yopishtirish — brend nazorati bilan.",
      "audience.3.chip": "HoReCa",
      "audience.3.t": "Zal to‘xtamasdan interyer",
      "audience.3.d": "Grafika va dekor tungi montaj bilan — obyekt ishlashda davom etadi.",
      "audience.4.chip": "Marketing",
      "audience.4.t": "Shoshilinch tiraj va aksiyalar",
      "audience.4.d": "Bosma, POSM va mobil konstruksiyalar kampaniya sanasiga.",
      "nav.clients": "Mijozlar",
      "nav.cta": "Hisob olish",
      "nav.menu": "Asosiy menyu",
      "nav.open": "Menyuni ochish",

      "hero.eyebrow": "Reklama ishlab chiqarish · O‘zbekiston",
      "hero.title": "Yorliqlar, POSM va obyekt bezashi — muddat buzilmasdan",
      "hero.lead": "O‘z sex, dizayn va montaj bitta shartnomada. Ish kuni odatda 4 soat ichida javob — O‘zbekiston bo‘ylab topshiramiz.",
      "hero.cta1": "Hisob olish",
      "hero.seg1": "Riteyl uchun",
      "hero.seg2": "Banklar uchun",
      "hero.seg3": "HoReCa uchun",
      "hero.cta2": "Keyslarni ko‘rish",
      "hero.chip1": "Bozorda 15+ yil",
      "hero.chip2": "Yiliga 1500 loyiha",
      "hero.chip3": "O‘z ishlab chiqarish",
      "hero.float1": "85 mutaxassis",
      "hero.float2": "1500 m² maydon",
      "hero.imgAlt": "GIGANT MEDIA reklama ishlab chiqarish",

      "about.eyebrow": "Kompaniya",
      "about.title": "Biz haqimizda",
      "about.p1":
        "GIGANT MEDIA — to‘liq tsikli reklama ishlab chiqarish. 15+ yil: dizayn, o‘z sex va O‘zbekiston bo‘ylab montaj.",
      "about.p2":
        "Tashqi reklama ishlab chiqarishda boy tajribaga egamiz. Binolar, ofislar va do‘konlar fasadi mutaxassislarimiz tufayli yangicha ko‘rinishga ega. Filiallarimiz butun O‘zbekiston bo‘ylab ochilgan.",
      "about.geo": "Faoliyat geografiyasi",
      "mosaic.eyebrow": "Ishlab chiqarish",
      "mosaic.title": "Sifat nazorati orqali ustunlik",
      "mosaic.1.t": "O‘z sex va muhandislik",
      "mosaic.1.d": "Bosma, metall va yig‘ish o‘z maydonlarimizda — ortiqcha pudratchilar zanjirisiz.",
      "mosaic.2.t": "Har bosqichda qabul",
      "mosaic.2.d": "Maket, rang namuna, ishlab chiqarish va montaj — topshirishdan oldin sifatni belgilaymiz.",
      "mosaic.3.t": "Maketdan montajgacha",
      "mosaic.more": "To‘liq o‘qish",
      "mosaic.cta": "Batafsil",
      "download.eyebrow": "Materiallar",
      "download.title": "Taqdimot va ish namunalarini olish",
      "download.lead": "Kontakt qoldiring — vazifangiz bo‘yicha keys va muddatlar yuboramiz.",
      "download.cta": "Material so‘rash",
      "download.wa": "WhatsApp yozish",
      "fab.call": "Qo‘ng‘iroq",

      "services.eyebrow": "Xizmatlar",
      "services.title": "Asosiy yo‘nalishlar",
      "services.lead": "To‘liq tsikldagi olti asosiy xizmat. Qolganlari — so‘rov bo‘yicha.",
      "services.more": "Batafsil →",
      "services.ask": "Hisob so‘rash →",
      "services.moreLabel": "Yana yo‘nalishlar",
      "services.moreCta": "Yo‘nalish bo‘yicha so‘rov",
      "services.note": "Kafolat xizmati va maslahat — loyiha topshirilgandan keyin ham.",
      "services.prev": "Orqaga",
      "services.next": "Oldinga",
      "services.s1.t": "Yorliqlar",
      "services.s1.d": "Hajmli harflar, yorug‘lik qutilari va fasad konstruksiyalari montaj bilan.",
      "services.s1.b": "Kalit topshirish",
      "services.s2.t": "POSM",
      "services.s2.d": "Shelf-tokerlar, stopperlar, dispenserlar va savdo nuqtasi materiallari.",
      "services.s2.b": "SKU e’tibori",
      "services.s3.t": "Yo‘l bo‘yi reklama",
      "services.s3.d": "Transport yo‘llari bo‘ylab shildlar va konstruksiyalar.",
      "services.s3.b": "Maksimal qamrov",
      "services.s4.t": "Mebel",
      "services.s4.d": "Savdo va ko‘rgazma mebeli — brend va obyekt vazifasiga mos.",
      "services.s4.b": "Brendinga mos",
      "services.s5.t": "Vobblerlar",
      "services.s5.d": "Tokchadagi mahsulotga e’tiborni jalb qiluvchi POS elementlar.",
      "services.s5.b": "Tez urg‘u",
      "services.s6.t": "Mobil stendlar",
      "services.s6.d": "Aksiya, forum va chiqish tadbirlari uchun konstruksiyalar.",
      "services.s6.b": "Joyida yig‘ish",
      "services.s7.t": "Dekor",
      "services.s7.d": "Interer, vitrina va brend zonalar uchun dekorativ yechimlar.",
      "services.s7.b": "Muhit yaratish",
      "services.s8.t": "Kukunli bo‘yash",
      "services.s8.d": "Metall konstruksiya va reklama buyumlari uchun mustahkam qoplama.",
      "services.s8.b": "Uzoq muddat",
      "services.s9.t": "Kompleks bezash",
      "services.s9.d": "Obyektni bezashning to‘liq tsikli: konsepsiyadan montajgacha.",
      "services.s9.b": "Bitta pudratchi",
      "services.s10.t": "Reklama yopishtirish",
      "services.s10.d": "Transport, vitrina va sirtlarni plyonka bilan brendlash.",
      "services.s10.b": "Aniq rang",
      "services.s11.t": "Keng formatli bosma",
      "services.s11.d": "Bannerlar, brend zonalar, ichki va tashqi grafika.",
      "services.s11.b": "Bosma nazorati",
      "services.s12.t": "Suvenir va mukofotlar",
      "services.s12.d": "Korporativ sovg‘alar, mukofotlar va suvenir mahsulotlar.",
      "services.s12.b": "Brend imidji",
      "services.s13.t": "Ko‘rgazma stendlari",
      "services.s13.d": "Ko‘rgazma stendlari va konstruksiyalari kalit topshirish asosida.",
      "services.s13.b": "Namoyishga tayyor",

      "clients.eyebrow": "Mijozlar",
      "clients.title": "Bizga ishonishadi",
      "clients.lead": "Butun O‘zbekiston bo‘ylab reklama ishlab chiqaradigan brendlar.",

      "cases.eyebrow": "Keyslar",
      "cases.title": "Natija — oddiy galereya emas",
      "cases.lead": "Vazifa, yechim va o‘lchovli effekt — ishimizni shunday ko‘rsatamiz.",
      "cases.c1.client": "Riteyl",
      "cases.c1.title": "Savdo zonasini bezash",
      "cases.c1.d": "Kompleks brend zona: yorliq, navigatsiya va POSM yagona uslubda.",
      "cases.c1.m1": "14 kun",
      "cases.c1.m1l": "bajarish muddati",
      "cases.c1.m2": "1 pudratchi",
      "cases.c1.m2l": "dizayn → montaj",
      "cases.c2.client": "Bank sektori",
      "cases.c2.title": "Fasad va kirish guruhi",
      "cases.c2.d": "Yorug‘lik konstruksiyalari va yopishtirish — rang va muddat nazorati bilan.",
      "cases.c2.m1": "21 kun",
      "cases.c2.m1l": "maketdan montajgacha",
      "cases.c2.m2": "±ΔE 2",
      "cases.c2.m2l": "brend rangi nazorati",
      "cases.c3.client": "HoReCa / kafe",
      "cases.c3.title": "Interer grafikasi",
      "cases.c3.d": "Muassasa ishini to‘xtatmasdan dekor va bosma.",
      "cases.c3.m1": "Tungi montaj",
      "cases.c3.m1l": "zal to‘xtamasdan",
      "cases.c3.m2": "3 zona",
      "cases.c3.m2l": "yagona vizual kod",
      "cases.link": "Keysni ko‘rish →",
      "cases.ask": "O‘xshash hisob olish →",

      "team.eyebrow": "Jamoa",
      "team.title": "Mutaxassislarimiz",
      "team.lead": "Xodimlar fotosi va profillari shu yerda bo‘ladi — blok to‘ldirishga tayyor.",
      "team.slotName": "Ism Familiya",
      "team.slotRole": "Lavozim",

      "process.eyebrow": "Jarayon",
      "process.title": "Qanday ishlaymiz",
      "process.lead": "Hisob-kitobdan kafolat xizmatigacha shaffof bosqichlar.",
      "process.1.t": "Brif va hisob",
      "process.1.d": "Vazifa, muddat, byudjet va texnik cheklovlarni belgilaymiz.",
      "process.2.t": "Dizayn va muhandislik",
      "process.2.d": "Dizayn bo‘limi va texnolog ishlab chiqarishga tayyor yechim beradi.",
      "process.3.t": "Ishlab chiqarish",
      "process.3.d": "Bosma, metall, bo‘yoq va yig‘ish — o‘z maydonlarimizda.",
      "process.4.t": "Montaj va servis",
      "process.4.d": "Obyektda o‘rnatish va topshirishdan keyin maslahat.",

      "numbers.eyebrow": "Masshtab",
      "numbers.title": "Raqamlarda biz",
      "numbers.lead": "O‘zbekiston mintaqalarida mavjud ishlab chiqarish kompaniyasi.",
      "numbers.1": "yiliga loyihalar",
      "numbers.2": "jamiyatdagi xodimlar",
      "numbers.3": "reklama bozoridagi yillar",
      "numbers.4": "ishlab chiqarish maydoni",

      "advantages.eyebrow": "Afzalliklar",
      "advantages.title": "Nega GIGANT MEDIA",
      "advantages.lead": "O‘z sex, o‘z dizayn va natija uchun javobgarlik.",
      "advantages.1.chip": "Ishlab chiqarish",
      "advantages.1.t": "O‘z seximiz",
      "advantages.1.d": "Ortiqcha pudratchilarsiz optimal narx va qisqa muddat.",
      "advantages.2.chip": "Tajriba",
      "advantages.2.t": "Individual yondashuv",
      "advantages.2.d": "Texnolog konstruksiya, byudjet va muddatni optimallashtiradi.",
      "advantages.3.chip": "Dizayn",
      "advantages.3.t": "O‘z dizayn bo‘limi",
      "advantages.3.d": "Har qanday mahsulot uchun professional maketlar.",

      "reviews.eyebrow": "Sharhlar",
      "reviews.title": "Mijozlar fikri",
      "reviews.lead": "Sifat, buyurtmani qayta ishlash tezligi va bashoratli narx.",
      "reviews.1.chip": "Mijoz",
      "reviews.1.q": "«Ajoyib sifat, buyurtmani qayta ishlash tezligi yuqori. Qulay narxlar. Yana murojaat qilaman.»",
      "reviews.1.n": "Ramil Rinatovich",
      "reviews.1.r": "Kompaniya direktori",
      "reviews.2.chip": "Ishlab chiqarish",
      "reviews.2.q": "«O‘z sex va dizayn borligi muhim: kamroq kelishuv, tezroq montaj.»",
      "reviews.2.n": "Aziz K.",
      "reviews.2.r": "Xaridlar bo‘limi rahbari, riteyl",
      "reviews.3.chip": "Xizmat",
      "reviews.3.q": "«Loyiha topshirilgandan keyin ham maslahat berishadi — bu kam uchraydi.»",
      "reviews.3.n": "Nigora M.",
      "reviews.3.r": "Brend-menejer, kafe tarmog‘i",

      "faq.eyebrow": "FAQ",
      "faq.title": "Ko‘p so‘raladigan savollar",
      "faq.lead": "Muddatlar, ishlab chiqarish va loyihani qanday boshlash haqida.",
      "faq.1.q": "Oddiy loyiha qancha vaqt oladi?",
      "faq.1.a": "Bosma/POSM uchun bir necha kundan kompleks bezash uchun 2–4 haftagacha — muddatni hisob bosqichida belgilaymiz.",
      "faq.2.q": "O‘z ishlab chiqarishingiz bormi?",
      "faq.2.a": "Ha. O‘z sex, dizayn bo‘limi va montaj jamoasi — sifat, muddat va narx nazorati.",
      "faq.3.q": "Hududlarda ishlaysizmi?",
      "faq.3.a": "Ha. Filiallar va loyihalar butun O‘zbekiston bo‘ylab: Toshkent, viloyat va asosiy shaharlar.",
      "faq.4.q": "Aniq hisob uchun nima kerak?",
      "faq.4.a": "Obyekt fotosi, manzil, taxminiy o‘lchamlar, format va referens (bo‘lsa). Qolganini qo‘ng‘iroqda aniqlaymiz.",
      "faq.5.q": "Noldan dizayn qilasizmi?",
      "faq.5.a": "Ha. Konsepsiya, maketlar va ishlab chiqarish uchun texnik fayllar — yoki brendbukingizni moslashtiramiz.",
      "faq.6.q": "Tashqi reklama kelishuvi bilan yordam berasizmi?",
      "faq.6.a": "Kelishuv uchun eskiz va texnik ma’lumot tayyorlaymiz. Talablar obyekt, fasad va konstruksiya turiga bog‘liq.",
      "faq.7.q": "Shoshilinch buyurtma mumkinmi?",
      "faq.7.a": "Ha, ishlab chiqarishda joy bo‘lsa. Shoshilinchlikni boshida kelishamiz va rejada belgilaymiz.",
      "faq.8.q": "Mahsulotlarga qanday kafolat?",
      "faq.8.a": "Topshirishdan keyin shartnoma bo‘yicha kafolat. Maket, rang, ishlab chiqarish va montaj bosqichlarida nazorat.",
      "faq.9.q": "Montajsiz faqat ishlab chiqarish mumkinmi?",
      "faq.9.a": "Ha. To‘liq tsikl yoki alohida bosqichlar: dizayn, ishlab chiqarish, montaj, element almashtirish.",
      "faq.10.q": "Arizaga qancha tez javob berasiz?",
      "faq.10.a": "Ish vaqtida odatda 4 soat ichida. Tungi va dam olish kunlari — keyingi ish kuni.",
      "trust.1": "Ish kuni javob · odatda 4 soatgacha",
      "trust.2": "Shartnoma va kafolat",
      "trust.3": "Chiqish / o‘lchov kelishuv asosida",
      "trust.4": "O‘zbekiston hududlarida montaj",
      "workshop.eyebrow": "Sex",
      "workshop.title": "O‘z ishlab chiqarish — subpudratchi emas",
      "workshop.lead": "Bosma, metall, bo‘yoq va yig‘ish o‘z maydonlarimizda.",
      "workshop.c1": "Ishlab chiqarish liniyasi",
      "workshop.c2": "Yig‘ish va nazorat",
      "workshop.c3": "Tayyor konstruksiyalar",
      "workshop.c4": "Bo‘yoq va finish",
      "workshop.c5": "Montajdan keyin obyektlar",
      "workshop.c6": "Yorliqlar va fasadlar",
      "seo.lb.t": "Yorug‘lik qutilari",
      "seo.lb.d": "LED qutilar va yorug‘lik konstruksiyalari — fasad va interyer, montaj bilan.",
      "seo.lb.b": "Yorqinlik va xizmat muddati",

      "contacts.eyebrow": "Aloqa",
      "contacts.title": "Hisob olish",
      "contacts.lead": "Kontaktlaringizni qoldiring — vazifani aniqlaymiz va ish vaqtida muddat bilan byudjet yuboramiz.",
      "contacts.trust1": "Ish kuni ichida javob · odatda 4 soatgacha",
      "contacts.trust2": "Shartnoma · topshirishdan keyin kafolat",
      "contacts.trust3": "Bitta pudratchi: dizayn → ishlab chiqarish → montaj",
      "contacts.phone": "Telefon",
      "contacts.more": "Qo‘shimcha",
      "contacts.address": "Manzil",
      "contacts.addressValue": "Toshkent, Yunusobod tumani, 9-mavze, Yuqori Qoraqamish ko‘chasi, 5A",
      "contacts.quick": "Tezkor aloqa",
      "contacts.whatsapp": "WhatsApp",
      "contacts.telegram": "Telegram",
      "contacts.email": "Email",
      "form.name": "Ism",
      "form.namePh": "Sizni qanday deb chaqiraylik",
      "form.phone": "Telefon",
      "form.phonePh": "+998 __ ___ __ __",
      "form.lang": "Muloqot tili",
      "form.langRu": "Ruscha",
      "form.langUz": "O‘zbekcha",
      "form.langEn": "English",
      "form.msg": "Vazifa",
      "form.msgPh": "Qisqa: obyekt, hajm, shahar",
      "form.submit": "Hisob olish",
      "form.task": "Vazifa turi",
      "form.taskPh": "Yo‘nalishni tanlang",
      "form.taskSigns": "Yorliqlar",
      "form.taskPosm": "POSM / bosma",
      "form.taskComplex": "Kompleks bezash",
      "form.taskOther": "Boshqa",
      "form.deadline": "Istalgan muddat",
      "form.deadlinePh": "Masalan: 15 avgustgacha",
      "form.errorTask": "Vazifa turini tanlang",
      "form.successWa": "WhatsApp yozish",
      "form.successCall": "Qo‘ng‘iroq",
      "form.note": "Tugmani bosib, ma’lumotlarga rozilik berasiz. Ish vaqtida qo‘ng‘iroq qilamiz.",
      "form.errorName": "Ismni kiriting",
      "form.errorPhone": "To‘g‘ri telefon raqamini kiriting",
      "form.success": "Ariza qabul qilindi. WhatsApp yoki qo‘ng‘iroq — tezroq.",
      "midCta.1.eyebrow": "Keyingi qadam",
      "midCta.1.title": "O‘xshash natija kerakmi?",
      "midCta.1.lead": "Vazifani yozing — ish kuni ichida hisob va muddat yuboramiz.",
      "midCta.1.cta": "Hisob olish",
      "midCta.2.eyebrow": "Xavfsiz",
      "midCta.2.title": "Bitta pudratchi — maketdan montajgacha",
      "midCta.2.lead": "O‘z sex, o‘z dizayn va topshirishdan keyin qo‘llab-quvvatlash. Ish vaqtida qo‘ng‘iroq qilamiz.",
      "sticky.cta": "Hisob",
      "sticky.wa": "WhatsApp",
      "form.sending": "Yuborilmoqda…",

      "footer.tagline": "To‘liq tsikli reklama-ishlab chiqarish kompaniyasi. Filiallar butun O‘zbekiston bo‘ylab.",
      "footer.menu": "Menyu",
      "footer.services": "Xizmatlar",
      "footer.contacts": "Aloqa",
      "footer.copy": "© GIGANT MEDIA",
      "footer.note": "To‘liq tsikli reklama ishlab chiqarish · O‘zbekiston",
      "footer.dev": "Sayt ishlab chiqish va targ‘iboti — <a href=\"https://t.me/webgiants\" target=\"_blank\" rel=\"noopener noreferrer\">t.me/webgiants</a>",

      "calc.skip": "Kalkulyatorga",
      "calc.eyebrow": "Narx hisobi",
      "calc.title": "Narx kalkulyatori",
      "calc.lead": "Reklama mahsulotlari uchun rasmiy narx hisobi. Mahsulot turi va parametrlarni tanlang. Yakuniy narx avtomatik yangilanadi.",
      "calc.home": "Bosh sahifaga",
      "calc.footer": "GIGANT MEDIA · Narx kalkulyatori",
      "lang.label": "Sayt tili",
    },
  },
};
