/* GIGANT MEDIA — multilingual content dictionary
   Default: Russian. Extend by adding keys to all locales. */
window.GM_CONTENT = {
  defaultLang: "ru",
  langs: ["ru", "en", "uz"],
  meta: {
    ru: {
      title: "GIGANT MEDIA — Рекламное производство полного цикла",
      description:
        "GIGANT MEDIA — рекламно-производственная компания полного цикла в Узбекистане: вывески, ПОСМ, печать, мебель, стенды. 15+ лет, своё производство, филиалы по стране.",
    },
    en: {
      title: "GIGANT MEDIA — Full-cycle advertising production",
      description:
        "GIGANT MEDIA is a full-cycle advertising and production company in Uzbekistan: signs, POSM, print, furniture, stands. 15+ years, in-house production, nationwide coverage.",
    },
    uz: {
      title: "GIGANT MEDIA — To‘liq tsikli reklama ishlab chiqarish",
      description:
        "GIGANT MEDIA — O‘zbekistondagi to‘liq tsikli reklama-ishlab chiqarish kompaniyasi: yorliqlar, POSM, bosma, mebel, stendlar. 15+ yil, o‘z ishlab chiqarish, butun mamlakat bo‘ylab filiallar.",
    },
  },
  dict: {
    ru: {
      "nav.home": "Главная",
      "nav.about": "О компании",
      "nav.services": "Услуги",
      "nav.cases": "Кейсы",
      "nav.advantages": "Преимущества",
      "nav.reviews": "Отзывы",
      "nav.faq": "FAQ",
      "nav.contacts": "Контакты",
      "nav.clients": "Клиенты",
      "nav.cta": "Оставить заявку",
      "nav.menu": "Основное меню",
      "nav.open": "Открыть меню",

      "hero.eyebrow": "Рекламное производство · Узбекистан",
      "hero.title": "Один подрядчик: дизайн, производство и монтаж",
      "hero.lead":
        "Без срыва сроков и цепочки субподрядчиков. Вывески, POSM, печать и оформление объектов по всему Узбекистану — расчёт в течение рабочего дня.",
      "hero.cta1": "Рассчитать за 24 часа",
      "hero.seg1": "Для ритейла",
      "hero.seg2": "Для банков",
      "hero.seg3": "Для HoReCa",
      "hero.cta2": "Смотреть кейсы",
      "hero.chip1": "15+ лет на рынке",
      "hero.chip2": "1500 проектов / год",
      "hero.chip3": "Собственное производство",
      "hero.float1": "85 специалистов",
      "hero.float2": "1500 м² площадей",
      "hero.imgAlt": "Производство рекламной продукции GIGANT MEDIA",

      "about.eyebrow": "Компания",
      "about.title": "О компании",
      "about.p1":
        "Рекламно-производственная компания полного цикла «GIGANT MEDIA» успешно работает на рекламном рынке более 15 лет и предлагает весь комплекс рекламных, полиграфических и дизайнерских услуг на высоком профессиональном уровне.",
      "about.p2":
        "За плечами — богатый опыт производства наружной рекламы. Многие фасады зданий, офисов и магазинов выглядят по-новому благодаря нашим специалистам. Филиалы открыты по всему Узбекистану.",
      "about.geo": "География присутствия",
      "mosaic.eyebrow": "Производство",
      "mosaic.title": "Превосходство через контроль качества",
      "mosaic.1.t": "Свой цех и инженерия",
      "mosaic.1.d": "Печать, металлоконструкции и сборка на своих площадях — без лишней цепочки подрядчиков.",
      "mosaic.2.t": "Приёмка на каждом этапе",
      "mosaic.2.d": "Макет, цветопроба, производство и монтаж — фиксируем качество до сдачи объекта.",
      "mosaic.3.t": "От макета до монтажа",
      "mosaic.more": "Читать полностью",
      "mosaic.cta": "Узнать больше",
      "download.eyebrow": "Материалы",
      "download.title": "Получить презентацию и примеры работ",
      "download.lead": "Оставьте контакты — пришлём подборку кейсов и ориентиры по срокам под вашу задачу.",
      "download.cta": "Запросить материалы",
      "download.wa": "Написать в WhatsApp",
      "fab.call": "Позвонить",

      "services.eyebrow": "Услуги",
      "services.title": "Ключевые направления",
      "services.lead":
        "Полный цикл: вывески, POSM, печать, мебель, стенды и комплексное оформление объектов.",
      "services.more": "Подробнее →",
      "services.ask": "Запросить расчёт →",
      "services.moreLabel": "Ещё направления",
      "services.moreCta": "Запросить по направлению",
      "services.note": "Гарантийное обслуживание и консультации — даже после сдачи проекта.",
      "services.prev": "Назад",
      "services.next": "Вперёд",
      "services.s1.t": "Вывески",
      "services.s1.d": "Объёмные буквы, световые короба и фасадные конструкции с монтажом.",
      "services.s1.b": "Монтаж под ключ",
      "services.s2.t": "ПОСМ",
      "services.s2.d": "Шелфтокеры, стопперы, диспенсеры и материалы для точки продаж.",
      "services.s2.b": "Рост внимания к SKU",
      "services.s3.t": "Придорожная реклама",
      "services.s3.d": "Щиты, конструкции и носители вдоль транспортных артерий.",
      "services.s3.b": "Максимальный охват",
      "services.s4.t": "Мебель",
      "services.s4.d": "Торговая и выставочная мебель под бренд и задачу объекта.",
      "services.s4.b": "Под ваш бренд",
      "services.s5.t": "Воблеры",
      "services.s5.d": "POS-элементы, которые привлекают внимание к товару на полке.",
      "services.s5.b": "Быстрый акцент",
      "services.s6.t": "Мобильные стенды",
      "services.s6.d": "Конструкции для акций, форумов и выездных мероприятий.",
      "services.s6.b": "Сборка на месте",
      "services.s7.t": "Декор",
      "services.s7.d": "Декоративные решения для интерьеров, витрин и бренд-зон.",
      "services.s7.b": "Атмосфера объекта",
      "services.s8.t": "Порошковая покраска",
      "services.s8.d": "Стойкое покрытие металлоконструкций и рекламных изделий.",
      "services.s8.b": "Долговечность",
      "services.s9.t": "Комплексное оформление",
      "services.s9.d": "Полный цикл оформления объекта: от концепции до монтажа.",
      "services.s9.b": "Один подрядчик",
      "services.s10.t": "Рекламная оклейка",
      "services.s10.d": "Брендирование транспорта, витрин и поверхностей плёнкой.",
      "services.s10.b": "Точный цвет",
      "services.s11.t": "Широкоформатная печать",
      "services.s11.d": "Баннеры, бренд-зоны, интерьерная и наружная графика.",
      "services.s11.b": "Контроль печати",
      "services.s12.t": "Сувениры и награды",
      "services.s12.d": "Корпоративные подарки, награды и сувенирная продукция.",
      "services.s12.b": "Имидж бренда",
      "services.s13.t": "Выставочные стенды",
      "services.s13.d": "Выставочные стенды и конструкции под ключ.",
      "services.s13.b": "Готово к показу",

      "clients.eyebrow": "Клиенты",
      "clients.title": "Нам доверяют",
      "clients.lead": "Бренды и компании, для которых мы производим рекламу по всему Узбекистану.",

      "cases.eyebrow": "Кейсы",
      "cases.title": "Результаты вместо сухого портфолио",
      "cases.lead": "Задача, решение и измеримый эффект — так мы показываем работу.",
      "cases.c1.client": "Ритейл",
      "cases.c1.title": "Оформление торговой зоны",
      "cases.c1.d": "Комплексная бренд-зона: вывеска, навигация и POSM в едином стиле.",
      "cases.c1.m1": "14 дней",
      "cases.c1.m1l": "срок реализации",
      "cases.c1.m2": "1 подрядчик",
      "cases.c1.m2l": "дизайн → монтаж",
      "cases.c2.client": "Банковский сектор",
      "cases.c2.title": "Фасад и входная группа",
      "cases.c2.d": "Световые конструкции и оклейка с контролем цвета и сроков.",
      "cases.c2.m1": "21 день",
      "cases.c2.m1l": "от макета до монтажа",
      "cases.c2.m2": "±ΔE 2",
      "cases.c2.m2l": "контроль цвета бренда",
      "cases.c3.client": "HoReCa / кафе",
      "cases.c3.title": "Интерьерная графика",
      "cases.c3.d": "Декор и печать для атмосферы заведения без остановки работы.",
      "cases.c3.m1": "Ночной монтаж",
      "cases.c3.m1l": "без простоя зала",
      "cases.c3.m2": "3 зоны",
      "cases.c3.m2l": "единый визуальный код",
      "cases.link": "Смотреть кейс →",
      "cases.ask": "Получить похожий расчёт →",

      "team.eyebrow": "Команда",
      "team.title": "Наши специалисты",
      "team.lead": "Фото и профили сотрудников появятся здесь — блок готов к наполнению.",
      "team.slotName": "Имя Фамилия",
      "team.slotRole": "Должность",

      "process.eyebrow": "Процесс",
      "process.title": "Как мы работаем",
      "process.lead": "Прозрачные этапы: от расчёта до гарантийного сопровождения.",
      "process.1.t": "Бриф и расчёт",
      "process.1.d": "Фиксируем задачу, сроки, бюджет и технические ограничения.",
      "process.2.t": "Дизайн и инженерия",
      "process.2.d": "Дизайн-отдел и технолог готовят решение под производство.",
      "process.3.t": "Производство",
      "process.3.d": "Печать, металлоконструкции, покраска и сборка на своих площадях.",
      "process.4.t": "Монтаж и сервис",
      "process.4.d": "Установка на объекте и консультации после сдачи проекта.",

      "numbers.eyebrow": "Масштаб",
      "numbers.title": "О нас в цифрах",
      "numbers.lead": "Производственная компания с присутствием по регионам Узбекистана.",
      "numbers.1": "проектов в год",
      "numbers.2": "сотрудников в команде",
      "numbers.3": "лет на рекламном рынке",
      "numbers.4": "производственных площадей",

      "advantages.eyebrow": "Преимущества",
      "advantages.title": "Почему выбирают GIGANT MEDIA",
      "advantages.lead": "Свой цех, свой дизайн и ответственность за результат.",
      "advantages.1.chip": "Производство",
      "advantages.1.t": "Собственный цех",
      "advantages.1.d": "Оптимальная стоимость и сжатые сроки без лишних подрядных звеньев.",
      "advantages.2.chip": "Экспертиза",
      "advantages.2.t": "Индивидуальный подход",
      "advantages.2.d": "Технолог помогает оптимизировать конструкцию, бюджет и сроки.",
      "advantages.3.chip": "Дизайн",
      "advantages.3.t": "Свой дизайн-отдел",
      "advantages.3.d": "Профессиональные макеты и визуалы под любую продукцию.",

      "reviews.eyebrow": "Отзывы",
      "reviews.title": "Слова клиентов",
      "reviews.lead": "Качество, скорость обработки заказа и предсказуемая цена.",
      "reviews.1.chip": "Клиент",
      "reviews.1.q": "«Отличное качество, скорость обработки заказа на высоте. Приемлемые цены. Обязательно обращусь снова.»",
      "reviews.1.n": "Рамиль Ринатович",
      "reviews.1.r": "Директор компании",
      "reviews.2.chip": "Производство",
      "reviews.2.q": "«Важно, что есть свой цех и дизайн: меньше согласований, быстрее выход на монтаж.»",
      "reviews.2.n": "Азиз К.",
      "reviews.2.r": "Руководитель отдела закупок, ритейл",
      "reviews.3.chip": "Сервис",
      "reviews.3.q": "«После сдачи проекта продолжают консультировать — это редкость и сильный аргумент.»",
      "reviews.3.n": "Нигора М.",
      "reviews.3.r": "Бренд-менеджер, сеть кафе",

      "faq.eyebrow": "FAQ",
      "faq.title": "Частые вопросы",
      "faq.lead": "Коротко о сроках, производстве и том, как стартовать проект.",
      "faq.1.q": "Сколько занимает типовой проект?",
      "faq.1.a": "От нескольких дней для печати и POSM до 2–4 недель для комплексного оформления — сроки фиксируем на этапе расчёта.",
      "faq.2.q": "У вас своё производство?",
      "faq.2.a": "Да. Собственный цех, дизайн-отдел и монтажные бригады — это контроль качества, сроков и стоимости.",
      "faq.3.q": "Работаете ли вы в регионах?",
      "faq.3.a": "Да. Филиалы и проекты по всему Узбекистану: Ташкент, область и ключевые города.",
      "faq.4.q": "Как оставить заявку?",
      "faq.4.a": "Заполните форму на сайте, позвоните или напишите в WhatsApp / Telegram — менеджер свяжется в рабочее время.",
      "faq.5.q": "Делаете ли дизайн с нуля?",
      "faq.5.a": "Да. Готовим концепцию, макеты и технические файлы под производство — или адаптируем ваш брендбук.",
      "faq.6.q": "Есть ли минимальный заказ?",
      "faq.6.a": "Зависит от типа работ. Для печати и POSM стартуем с небольших тиражей; для конструкций — от объёма проекта.",
      "faq.7.q": "Можно ли срочный заказ?",
      "faq.7.a": "Да, при наличии слотов в производстве. Срочность согласуем на старте и зафиксируем в плане работ.",
      "faq.8.q": "Какие гарантии по качеству?",
      "faq.8.a": "Контроль на каждом этапе: макет, цветопроба, производство и приёмка монтажа. Доработки по гарантии — по договору.",

      "contacts.eyebrow": "Контакты",
      "contacts.title": "Получить расчёт",
      "contacts.lead": "Оставьте контакты — уточним задачу и пришлём сроки с бюджетом в рабочее время.",
      "contacts.trust1": "Ответ в рабочее время · обычно в течение дня",
      "contacts.trust2": "Гарантия и консультации после сдачи",
      "contacts.trust3": "Один подрядчик: дизайн → производство → монтаж",
      "contacts.phone": "Телефон",
      "contacts.more": "Дополнительно",
      "contacts.address": "Адрес",
      "contacts.addressValue": "г. Ташкент, Юнусабадский район, 9 квартал, ул. Юкори Каракамыш, 5А",
      "contacts.quick": "Быстрая связь",
      "contacts.whatsapp": "WhatsApp",
      "contacts.telegram": "Telegram",
      "contacts.email": "Email",
      "form.name": "Имя",
      "form.namePh": "Как к вам обращаться",
      "form.phone": "Телефон",
      "form.phonePh": "+998 __ ___ __ __",
      "form.lang": "Язык общения",
      "form.langRu": "Русский",
      "form.langUz": "Узбекский",
      "form.langEn": "English",
      "form.msg": "Задача",
      "form.msgPh": "Коротко: объект, объём, город",
      "form.submit": "Получить расчёт",
      "form.task": "Тип задачи",
      "form.taskPh": "Выберите направление",
      "form.taskSigns": "Вывески",
      "form.taskPosm": "POSM / печать",
      "form.taskComplex": "Комплексное оформление",
      "form.taskOther": "Другое",
      "form.deadline": "Желаемый срок",
      "form.deadlinePh": "Например: до 15 августа",
      "form.errorTask": "Выберите тип задачи",
      "form.successWa": "Написать в WhatsApp",
      "form.successCall": "Позвонить",
      "form.note": "Нажимая кнопку, вы соглашаетесь на обработку данных. Перезвоним в рабочее время.",
      "form.errorName": "Укажите имя",
      "form.errorPhone": "Укажите корректный телефон",
      "form.success": "Заявка принята. Можете сразу написать в WhatsApp или позвонить — так быстрее.",
      "midCta.1.eyebrow": "Следующий шаг",
      "midCta.1.title": "Нужен похожий результат?",
      "midCta.1.lead": "Опишите задачу — пришлём расчёт и сроки в течение рабочего дня.",
      "midCta.1.cta": "Получить расчёт",
      "midCta.2.eyebrow": "Без риска",
      "midCta.2.title": "Один подрядчик — от макета до монтажа",
      "midCta.2.lead": "Свой цех, свой дизайн и сопровождение после сдачи. Перезвоним в рабочее время.",
      "sticky.cta": "Заявка",
      "sticky.wa": "WhatsApp",
      "form.sending": "Отправляем…",

      "footer.tagline": "Рекламно-производственная компания полного цикла. Филиалы по всему Узбекистану.",
      "footer.menu": "Меню",
      "footer.services": "Услуги",
      "footer.contacts": "Контакты",
      "footer.copy": "© GIGANT MEDIA",
      "footer.note": "Full-cycle advertising production · Uzbekistan",
      "lang.label": "Язык сайта",
    },

    en: {
      "nav.home": "Home",
      "nav.about": "About",
      "nav.services": "Services",
      "nav.cases": "Cases",
      "nav.advantages": "Advantages",
      "nav.reviews": "Reviews",
      "nav.faq": "FAQ",
      "nav.contacts": "Contact",
      "nav.clients": "Clients",
      "nav.cta": "Request a quote",
      "nav.menu": "Main menu",
      "nav.open": "Open menu",

      "hero.eyebrow": "Advertising production · Uzbekistan",
      "hero.title": "One contractor: design, production and installation",
      "hero.lead":
        "No missed deadlines or subcontractor chains. Signs, POSM, print and object branding across Uzbekistan — estimate within one business day.",
      "hero.cta1": "Get an estimate in 24h",
      "hero.seg1": "For retail",
      "hero.seg2": "For banks",
      "hero.seg3": "For HoReCa",
      "hero.cta2": "View cases",
      "hero.chip1": "15+ years on the market",
      "hero.chip2": "1,500 projects / year",
      "hero.chip3": "In-house production",
      "hero.float1": "85 specialists",
      "hero.float2": "1,500 m² facilities",
      "hero.imgAlt": "GIGANT MEDIA advertising production",

      "about.eyebrow": "Company",
      "about.title": "About us",
      "about.p1":
        "GIGANT MEDIA is a full-cycle advertising and production company with 15+ years on the market. We deliver advertising, print and design services at a professional quality level.",
      "about.p2":
        "We have deep experience in outdoor advertising. Facades of offices and stores look new thanks to our team. Branches are open across Uzbekistan.",
      "about.geo": "Coverage geography",
      "mosaic.eyebrow": "Production",
      "mosaic.title": "Excellence through quality control",
      "mosaic.1.t": "Own workshop and engineering",
      "mosaic.1.d": "Print, metalwork and assembly on our floors — without an extra contractor chain.",
      "mosaic.2.t": "Checks at every stage",
      "mosaic.2.d": "Artwork, color proof, production and install — quality locked before handover.",
      "mosaic.3.t": "From artwork to install",
      "mosaic.more": "Read more",
      "mosaic.cta": "Learn more",
      "download.eyebrow": "Materials",
      "download.title": "Get a presentation and work samples",
      "download.lead": "Leave your contacts — we will send a case selection and timing for your brief.",
      "download.cta": "Request materials",
      "download.wa": "Message on WhatsApp",
      "fab.call": "Call",

      "services.eyebrow": "Services",
      "services.title": "Key directions",
      "services.lead": "Full cycle: signs, POSM, print, furniture, stands and complex object branding.",
      "services.more": "Learn more →",
      "services.ask": "Request an estimate →",
      "services.moreLabel": "More directions",
      "services.moreCta": "Request by direction",
      "services.note": "Warranty support and consulting — even after project handover.",
      "services.prev": "Previous",
      "services.next": "Next",
      "services.s1.t": "Signs",
      "services.s1.d": "Dimensional letters, lightboxes and facade structures with installation.",
      "services.s1.b": "Turnkey install",
      "services.s2.t": "POSM",
      "services.s2.d": "Shelf talkers, stoppers, dispensers and in-store materials.",
      "services.s2.b": "SKU attention",
      "services.s3.t": "Roadside ads",
      "services.s3.d": "Boards and structures along major traffic routes.",
      "services.s3.b": "Maximum reach",
      "services.s4.t": "Furniture",
      "services.s4.d": "Retail and exhibition furniture tailored to brand and space.",
      "services.s4.b": "Brand-fit build",
      "services.s5.t": "Wobblers",
      "services.s5.d": "POS elements that pull attention to products on the shelf.",
      "services.s5.b": "Fast highlight",
      "services.s6.t": "Mobile stands",
      "services.s6.d": "Structures for promotions, forums and field events.",
      "services.s6.b": "On-site setup",
      "services.s7.t": "Decor",
      "services.s7.d": "Decorative solutions for interiors, windows and brand zones.",
      "services.s7.b": "Space atmosphere",
      "services.s8.t": "Powder coating",
      "services.s8.d": "Durable coating for metal structures and advertising products.",
      "services.s8.b": "Long lifespan",
      "services.s9.t": "Complex branding",
      "services.s9.d": "Full object branding cycle: from concept to installation.",
      "services.s9.b": "One contractor",
      "services.s10.t": "Wrapping",
      "services.s10.d": "Vehicle, window and surface branding with vinyl.",
      "services.s10.b": "Color accuracy",
      "services.s11.t": "Wide-format print",
      "services.s11.d": "Banners, brand zones, indoor and outdoor graphics.",
      "services.s11.b": "Print control",
      "services.s12.t": "Souvenirs & awards",
      "services.s12.d": "Corporate gifts, awards and souvenir products.",
      "services.s12.b": "Brand image",
      "services.s13.t": "Exhibition stands",
      "services.s13.d": "Exhibition stands and structures delivered turnkey.",
      "services.s13.b": "Show-ready",

      "clients.eyebrow": "Clients",
      "clients.title": "Trusted by brands",
      "clients.lead": "Companies we produce advertising for across Uzbekistan.",

      "cases.eyebrow": "Cases",
      "cases.title": "Results instead of a flat gallery",
      "cases.lead": "Challenge, solution and measurable outcome — how we present work.",
      "cases.c1.client": "Retail",
      "cases.c1.title": "Retail zone branding",
      "cases.c1.d": "Full brand zone: signage, navigation and POSM in one system.",
      "cases.c1.m1": "14 days",
      "cases.c1.m1l": "delivery time",
      "cases.c1.m2": "1 contractor",
      "cases.c1.m2l": "design → install",
      "cases.c2.client": "Banking",
      "cases.c2.title": "Facade & entrance group",
      "cases.c2.d": "Light structures and wrapping with color and deadline control.",
      "cases.c2.m1": "21 days",
      "cases.c2.m1l": "from artwork to install",
      "cases.c2.m2": "±ΔE 2",
      "cases.c2.m2l": "brand color control",
      "cases.c3.client": "HoReCa / cafe",
      "cases.c3.title": "Interior graphics",
      "cases.c3.d": "Decor and print that keep the venue running during works.",
      "cases.c3.m1": "Night install",
      "cases.c3.m1l": "no venue downtime",
      "cases.c3.m2": "3 zones",
      "cases.c3.m2l": "one visual system",
      "cases.link": "View case →",
      "cases.ask": "Get a similar estimate →",

      "team.eyebrow": "Team",
      "team.title": "Our specialists",
      "team.lead": "Photos and profiles will appear here — the block is ready to fill.",
      "team.slotName": "Full name",
      "team.slotRole": "Role",

      "process.eyebrow": "Process",
      "process.title": "How we work",
      "process.lead": "Clear stages from estimate to after-sales support.",
      "process.1.t": "Brief & estimate",
      "process.1.d": "We lock scope, deadlines, budget and technical constraints.",
      "process.2.t": "Design & engineering",
      "process.2.d": "Designers and technologists prepare a production-ready solution.",
      "process.3.t": "Production",
      "process.3.d": "Print, metalwork, coating and assembly in our own facilities.",
      "process.4.t": "Install & service",
      "process.4.d": "On-site installation and consulting after handover.",

      "numbers.eyebrow": "Scale",
      "numbers.title": "By the numbers",
      "numbers.lead": "A production company with regional presence across Uzbekistan.",
      "numbers.1": "projects per year",
      "numbers.2": "people on the team",
      "numbers.3": "years on the market",
      "numbers.4": "of production space",

      "advantages.eyebrow": "Advantages",
      "advantages.title": "Why choose GIGANT MEDIA",
      "advantages.lead": "In-house workshop, in-house design and ownership of results.",
      "advantages.1.chip": "Production",
      "advantages.1.t": "Own workshop",
      "advantages.1.d": "Better cost and shorter lead times without extra subcontractors.",
      "advantages.2.chip": "Expertise",
      "advantages.2.t": "Individual approach",
      "advantages.2.d": "A technologist helps optimize construction, budget and timing.",
      "advantages.3.chip": "Design",
      "advantages.3.t": "In-house design team",
      "advantages.3.d": "Professional layouts and visuals for any product line.",

      "reviews.eyebrow": "Reviews",
      "reviews.title": "Client feedback",
      "reviews.lead": "Quality, order speed and predictable pricing.",
      "reviews.1.chip": "Client",
      "reviews.1.q": "“Excellent quality and fast order handling. Fair prices. I will come back.”",
      "reviews.1.n": "Ramil Rinatovich",
      "reviews.1.r": "Company director",
      "reviews.2.chip": "Production",
      "reviews.2.q": "“Having an in-house workshop and design means fewer handoffs and faster install.”",
      "reviews.2.n": "Aziz K.",
      "reviews.2.r": "Procurement lead, retail",
      "reviews.3.chip": "Service",
      "reviews.3.q": "“They keep consulting after handover — rare and valuable.”",
      "reviews.3.n": "Nigora M.",
      "reviews.3.r": "Brand manager, cafe chain",

      "faq.eyebrow": "FAQ",
      "faq.title": "Frequently asked questions",
      "faq.lead": "Timelines, production and how to start a project.",
      "faq.1.q": "How long does a typical project take?",
      "faq.1.a": "From a few days for print/POSM to 2–4 weeks for complex branding — we lock timelines at estimate stage.",
      "faq.2.q": "Do you have in-house production?",
      "faq.2.a": "Yes. Own workshop, design team and install crews — quality, deadlines and cost under one roof.",
      "faq.3.q": "Do you work in the regions?",
      "faq.3.a": "Yes. Branches and projects across Uzbekistan: Tashkent, the region and key cities.",
      "faq.4.q": "How do I send a request?",
      "faq.4.a": "Use the form, call us or message on WhatsApp / Telegram — a manager will reply in business hours.",
      "faq.5.q": "Do you design from scratch?",
      "faq.5.a": "Yes. Concept, artwork and production-ready files — or we adapt your brand guidelines.",
      "faq.6.q": "Is there a minimum order?",
      "faq.6.a": "It depends on the work type. Print/POSM can start small; structures scale with project scope.",
      "faq.7.q": "Can you handle rush jobs?",
      "faq.7.a": "Yes, when production slots are available. We confirm urgency upfront and lock it into the plan.",
      "faq.8.q": "What quality guarantees do you give?",
      "faq.8.a": "Checks at every stage: artwork, color proof, production and install handover. Warranty fixes per contract.",

      "contacts.eyebrow": "Contact",
      "contacts.title": "Get an estimate",
      "contacts.lead": "Leave your contacts — we clarify the brief and send timing with budget in business hours.",
      "contacts.trust1": "Reply in business hours · usually same day",
      "contacts.trust2": "Warranty and consulting after handover",
      "contacts.trust3": "One contractor: design → production → install",
      "contacts.phone": "Phone",
      "contacts.more": "Also",
      "contacts.address": "Address",
      "contacts.addressValue": "Tashkent, Yunusabad district, 9th quarter, Yukori Karakamysh st., 5A",
      "contacts.quick": "Quick contact",
      "contacts.whatsapp": "WhatsApp",
      "contacts.telegram": "Telegram",
      "contacts.email": "Email",
      "form.name": "Name",
      "form.namePh": "How should we address you",
      "form.phone": "Phone",
      "form.phonePh": "+998 __ ___ __ __",
      "form.lang": "Preferred language",
      "form.langRu": "Russian",
      "form.langUz": "Uzbek",
      "form.langEn": "English",
      "form.msg": "Project brief",
      "form.msgPh": "Briefly: site, scope, city",
      "form.submit": "Get an estimate",
      "form.task": "Task type",
      "form.taskPh": "Choose a direction",
      "form.taskSigns": "Signs",
      "form.taskPosm": "POSM / print",
      "form.taskComplex": "Complex branding",
      "form.taskOther": "Other",
      "form.deadline": "Desired deadline",
      "form.deadlinePh": "E.g. by August 15",
      "form.errorTask": "Choose a task type",
      "form.successWa": "Message on WhatsApp",
      "form.successCall": "Call",
      "form.note": "By submitting you agree to data processing. We call back in business hours.",
      "form.errorName": "Please enter your name",
      "form.errorPhone": "Please enter a valid phone number",
      "form.success": "Request received. Message us on WhatsApp or call — it’s faster.",
      "midCta.1.eyebrow": "Next step",
      "midCta.1.title": "Need a similar result?",
      "midCta.1.lead": "Describe the brief — we send estimate and timing within a business day.",
      "midCta.1.cta": "Get an estimate",
      "midCta.2.eyebrow": "Low risk",
      "midCta.2.title": "One contractor — from artwork to install",
      "midCta.2.lead": "Own workshop, in-house design and post-handover support. We call back in business hours.",
      "sticky.cta": "Request",
      "sticky.wa": "WhatsApp",
      "form.sending": "Sending…",

      "footer.tagline": "Full-cycle advertising and production company. Branches across Uzbekistan.",
      "footer.menu": "Menu",
      "footer.services": "Services",
      "footer.contacts": "Contacts",
      "footer.copy": "© GIGANT MEDIA",
      "footer.note": "Full-cycle advertising production · Uzbekistan",
      "lang.label": "Site language",
    },

    uz: {
      "nav.home": "Bosh sahifa",
      "nav.about": "Kompaniya",
      "nav.services": "Xizmatlar",
      "nav.cases": "Keyslar",
      "nav.advantages": "Afzalliklar",
      "nav.reviews": "Sharhlar",
      "nav.faq": "FAQ",
      "nav.contacts": "Aloqa",
      "nav.clients": "Mijozlar",
      "nav.cta": "Ariza qoldirish",
      "nav.menu": "Asosiy menyu",
      "nav.open": "Menyuni ochish",

      "hero.eyebrow": "Reklama ishlab chiqarish · O‘zbekiston",
      "hero.title": "Bitta pudratchi: dizayn, ishlab chiqarish va montaj",
      "hero.lead":
        "Muddat buzilishi va ortiqcha pudratchilarsiz. Yorliq, POSM, bosma va obyekt bezashi butun O‘zbekiston bo‘ylab — ish kuni ichida hisob.",
      "hero.cta1": "24 soatda hisob",
      "hero.seg1": "Riteyl uchun",
      "hero.seg2": "Banklar uchun",
      "hero.seg3": "HoReCa uchun",
      "hero.cta2": "Keyslarni ko‘rish",
      "hero.chip1": "Bozorda 15+ yil",
      "hero.chip2": "Yiliga 1500 loyiha",
      "hero.chip3": "O‘z ishlab chiqarish",
      "hero.float1": "85 mutaxassis",
      "hero.float2": "1500 m² maydon",
      "hero.imgAlt": "GIGANT MEDIA reklama ishlab chiqarish",

      "about.eyebrow": "Kompaniya",
      "about.title": "Biz haqimizda",
      "about.p1":
        "«GIGANT MEDIA» to‘liq tsikli reklama-ishlab chiqarish kompaniyasi 15 yildan ortiq reklama bozorida faoliyat yuritadi va yuqori sifatli reklama, matbaa va dizayn xizmatlarini taklif qiladi.",
      "about.p2":
        "Tashqi reklama ishlab chiqarishda boy tajribaga egamiz. Binolar, ofislar va do‘konlar fasadi mutaxassislarimiz tufayli yangicha ko‘rinishga ega. Filiallarimiz butun O‘zbekiston bo‘ylab ochilgan.",
      "about.geo": "Faoliyat geografiyasi",
      "mosaic.eyebrow": "Ishlab chiqarish",
      "mosaic.title": "Sifat nazorati orqali ustunlik",
      "mosaic.1.t": "O‘z sex va muhandislik",
      "mosaic.1.d": "Bosma, metall va yig‘ish o‘z maydonlarimizda — ortiqcha pudratchilar zanjirisiz.",
      "mosaic.2.t": "Har bosqichda qabul",
      "mosaic.2.d": "Maket, rang namuna, ishlab chiqarish va montaj — topshirishdan oldin sifatni belgilaymiz.",
      "mosaic.3.t": "Maketdan montajgacha",
      "mosaic.more": "To‘liq o‘qish",
      "mosaic.cta": "Batafsil",
      "download.eyebrow": "Materiallar",
      "download.title": "Taqdimot va ish namunalarini olish",
      "download.lead": "Kontakt qoldiring — vazifangiz bo‘yicha keys va muddatlar yuboramiz.",
      "download.cta": "Material so‘rash",
      "download.wa": "WhatsApp yozish",
      "fab.call": "Qo‘ng‘iroq",

      "services.eyebrow": "Xizmatlar",
      "services.title": "Asosiy yo‘nalishlar",
      "services.lead": "To‘liq tsikl: yorliqlar, POSM, bosma, mebel, stendlar va kompleks bezash.",
      "services.more": "Batafsil →",
      "services.ask": "Hisob so‘rash →",
      "services.moreLabel": "Yana yo‘nalishlar",
      "services.moreCta": "Yo‘nalish bo‘yicha so‘rov",
      "services.note": "Kafolat xizmati va maslahat — loyiha topshirilgandan keyin ham.",
      "services.prev": "Orqaga",
      "services.next": "Oldinga",
      "services.s1.t": "Yorliqlar",
      "services.s1.d": "Hajmli harflar, yorug‘lik qutilari va fasad konstruksiyalari montaj bilan.",
      "services.s1.b": "Kalit topshirish",
      "services.s2.t": "POSM",
      "services.s2.d": "Shelf-tokerlar, stopperlar, dispenserlar va savdo nuqtasi materiallari.",
      "services.s2.b": "SKU e’tibori",
      "services.s3.t": "Yo‘l bo‘yi reklama",
      "services.s3.d": "Transport yo‘llari bo‘ylab shildlar va konstruksiyalar.",
      "services.s3.b": "Maksimal qamrov",
      "services.s4.t": "Mebel",
      "services.s4.d": "Savdo va ko‘rgazma mebeli — brend va obyekt vazifasiga mos.",
      "services.s4.b": "Brendinga mos",
      "services.s5.t": "Vobblerlar",
      "services.s5.d": "Tokchadagi mahsulotga e’tiborni jalb qiluvchi POS elementlar.",
      "services.s5.b": "Tez urg‘u",
      "services.s6.t": "Mobil stendlar",
      "services.s6.d": "Aksiya, forum va chiqish tadbirlari uchun konstruksiyalar.",
      "services.s6.b": "Joyida yig‘ish",
      "services.s7.t": "Dekor",
      "services.s7.d": "Interer, vitrina va brend zonalar uchun dekorativ yechimlar.",
      "services.s7.b": "Muhit yaratish",
      "services.s8.t": "Kukunli bo‘yash",
      "services.s8.d": "Metall konstruksiya va reklama buyumlari uchun mustahkam qoplama.",
      "services.s8.b": "Uzoq muddat",
      "services.s9.t": "Kompleks bezash",
      "services.s9.d": "Obyektni bezashning to‘liq tsikli: konsepsiyadan montajgacha.",
      "services.s9.b": "Bitta pudratchi",
      "services.s10.t": "Reklama yopishtirish",
      "services.s10.d": "Transport, vitrina va sirtlarni plyonka bilan brendlash.",
      "services.s10.b": "Aniq rang",
      "services.s11.t": "Keng formatli bosma",
      "services.s11.d": "Bannerlar, brend zonalar, ichki va tashqi grafika.",
      "services.s11.b": "Bosma nazorati",
      "services.s12.t": "Suvenir va mukofotlar",
      "services.s12.d": "Korporativ sovg‘alar, mukofotlar va suvenir mahsulotlar.",
      "services.s12.b": "Brend imidji",
      "services.s13.t": "Ko‘rgazma stendlari",
      "services.s13.d": "Ko‘rgazma stendlari va konstruksiyalari kalit topshirish asosida.",
      "services.s13.b": "Namoyishga tayyor",

      "clients.eyebrow": "Mijozlar",
      "clients.title": "Bizga ishonishadi",
      "clients.lead": "Butun O‘zbekiston bo‘ylab reklama ishlab chiqaradigan brendlar.",

      "cases.eyebrow": "Keyslar",
      "cases.title": "Natija — oddiy galereya emas",
      "cases.lead": "Vazifa, yechim va o‘lchovli effekt — ishimizni shunday ko‘rsatamiz.",
      "cases.c1.client": "Riteyl",
      "cases.c1.title": "Savdo zonasini bezash",
      "cases.c1.d": "Kompleks brend zona: yorliq, navigatsiya va POSM yagona uslubda.",
      "cases.c1.m1": "14 kun",
      "cases.c1.m1l": "bajarish muddati",
      "cases.c1.m2": "1 pudratchi",
      "cases.c1.m2l": "dizayn → montaj",
      "cases.c2.client": "Bank sektori",
      "cases.c2.title": "Fasad va kirish guruhi",
      "cases.c2.d": "Yorug‘lik konstruksiyalari va yopishtirish — rang va muddat nazorati bilan.",
      "cases.c2.m1": "21 kun",
      "cases.c2.m1l": "maketdan montajgacha",
      "cases.c2.m2": "±ΔE 2",
      "cases.c2.m2l": "brend rangi nazorati",
      "cases.c3.client": "HoReCa / kafe",
      "cases.c3.title": "Interer grafikasi",
      "cases.c3.d": "Muassasa ishini to‘xtatmasdan dekor va bosma.",
      "cases.c3.m1": "Tungi montaj",
      "cases.c3.m1l": "zal to‘xtamasdan",
      "cases.c3.m2": "3 zona",
      "cases.c3.m2l": "yagona vizual kod",
      "cases.link": "Keysni ko‘rish →",
      "cases.ask": "O‘xshash hisob olish →",

      "team.eyebrow": "Jamoa",
      "team.title": "Mutaxassislarimiz",
      "team.lead": "Xodimlar fotosi va profillari shu yerda bo‘ladi — blok to‘ldirishga tayyor.",
      "team.slotName": "Ism Familiya",
      "team.slotRole": "Lavozim",

      "process.eyebrow": "Jarayon",
      "process.title": "Qanday ishlaymiz",
      "process.lead": "Hisob-kitobdan kafolat xizmatigacha shaffof bosqichlar.",
      "process.1.t": "Brif va hisob",
      "process.1.d": "Vazifa, muddat, byudjet va texnik cheklovlarni belgilaymiz.",
      "process.2.t": "Dizayn va muhandislik",
      "process.2.d": "Dizayn bo‘limi va texnolog ishlab chiqarishga tayyor yechim beradi.",
      "process.3.t": "Ishlab chiqarish",
      "process.3.d": "Bosma, metall, bo‘yoq va yig‘ish — o‘z maydonlarimizda.",
      "process.4.t": "Montaj va servis",
      "process.4.d": "Obyektda o‘rnatish va topshirishdan keyin maslahat.",

      "numbers.eyebrow": "Masshtab",
      "numbers.title": "Raqamlarda biz",
      "numbers.lead": "O‘zbekiston mintaqalarida mavjud ishlab chiqarish kompaniyasi.",
      "numbers.1": "yiliga loyihalar",
      "numbers.2": "jamiyatdagi xodimlar",
      "numbers.3": "reklama bozoridagi yillar",
      "numbers.4": "ishlab chiqarish maydoni",

      "advantages.eyebrow": "Afzalliklar",
      "advantages.title": "Nega GIGANT MEDIA",
      "advantages.lead": "O‘z sex, o‘z dizayn va natija uchun javobgarlik.",
      "advantages.1.chip": "Ishlab chiqarish",
      "advantages.1.t": "O‘z seximiz",
      "advantages.1.d": "Ortiqcha pudratchilarsiz optimal narx va qisqa muddat.",
      "advantages.2.chip": "Tajriba",
      "advantages.2.t": "Individual yondashuv",
      "advantages.2.d": "Texnolog konstruksiya, byudjet va muddatni optimallashtiradi.",
      "advantages.3.chip": "Dizayn",
      "advantages.3.t": "O‘z dizayn bo‘limi",
      "advantages.3.d": "Har qanday mahsulot uchun professional maketlar.",

      "reviews.eyebrow": "Sharhlar",
      "reviews.title": "Mijozlar fikri",
      "reviews.lead": "Sifat, buyurtmani qayta ishlash tezligi va bashoratli narx.",
      "reviews.1.chip": "Mijoz",
      "reviews.1.q": "«Ajoyib sifat, buyurtmani qayta ishlash tezligi yuqori. Qulay narxlar. Yana murojaat qilaman.»",
      "reviews.1.n": "Ramil Rinatovich",
      "reviews.1.r": "Kompaniya direktori",
      "reviews.2.chip": "Ishlab chiqarish",
      "reviews.2.q": "«O‘z sex va dizayn borligi muhim: kamroq kelishuv, tezroq montaj.»",
      "reviews.2.n": "Aziz K.",
      "reviews.2.r": "Xaridlar bo‘limi rahbari, riteyl",
      "reviews.3.chip": "Xizmat",
      "reviews.3.q": "«Loyiha topshirilgandan keyin ham maslahat berishadi — bu kam uchraydi.»",
      "reviews.3.n": "Nigora M.",
      "reviews.3.r": "Brend-menejer, kafe tarmog‘i",

      "faq.eyebrow": "FAQ",
      "faq.title": "Ko‘p so‘raladigan savollar",
      "faq.lead": "Muddatlar, ishlab chiqarish va loyihani qanday boshlash haqida.",
      "faq.1.q": "Oddiy loyiha qancha vaqt oladi?",
      "faq.1.a": "Bosma/POSM uchun bir necha kundan kompleks bezash uchun 2–4 haftagacha — muddatni hisob bosqichida belgilaymiz.",
      "faq.2.q": "O‘z ishlab chiqarishingiz bormi?",
      "faq.2.a": "Ha. O‘z sex, dizayn bo‘limi va montaj jamoasi — sifat, muddat va narx nazorati.",
      "faq.3.q": "Hududlarda ishlaysizmi?",
      "faq.3.a": "Ha. Filiallar va loyihalar butun O‘zbekiston bo‘ylab: Toshkent, viloyat va asosiy shaharlar.",
      "faq.4.q": "Arizani qanday qoldirish mumkin?",
      "faq.4.a": "Saytdagi forma, qo‘ng‘iroq yoki WhatsApp / Telegram — menejer ish vaqtida bog‘lanadi.",
      "faq.5.q": "Noldan dizayn qilasizmi?",
      "faq.5.a": "Ha. Konsepsiya, maketlar va ishlab chiqarish uchun texnik fayllar — yoki brendbukingizni moslashtiramiz.",
      "faq.6.q": "Minimal buyurtma bormi?",
      "faq.6.a": "Ish turiga bog‘liq. Bosma/POSM uchun kichik tirajdan boshlaymiz; konstruksiyalar — loyiha hajmiga qarab.",
      "faq.7.q": "Shoshilinch buyurtma mumkinmi?",
      "faq.7.a": "Ha, ishlab chiqarishda joy bo‘lsa. Shoshilinchlikni boshida kelishamiz va rejada belgilaymiz.",
      "faq.8.q": "Sifat kafolati qanday?",
      "faq.8.a": "Har bosqichda nazorat: maket, rang namunasi, ishlab chiqarish va montaj qabul qilish. Kafolat tuzatishlari — shartnoma bo‘yicha.",

      "contacts.eyebrow": "Aloqa",
      "contacts.title": "Hisob olish",
      "contacts.lead": "Kontaktlaringizni qoldiring — vazifani aniqlaymiz va ish vaqtida muddat bilan byudjet yuboramiz.",
      "contacts.trust1": "Ish vaqtida javob · odatda kun ichida",
      "contacts.trust2": "Topshirishdan keyin kafolat va maslahat",
      "contacts.trust3": "Bitta pudratchi: dizayn → ishlab chiqarish → montaj",
      "contacts.phone": "Telefon",
      "contacts.more": "Qo‘shimcha",
      "contacts.address": "Manzil",
      "contacts.addressValue": "Toshkent, Yunusobod tumani, 9-mavze, Yuqori Qoraqamish ko‘chasi, 5A",
      "contacts.quick": "Tezkor aloqa",
      "contacts.whatsapp": "WhatsApp",
      "contacts.telegram": "Telegram",
      "contacts.email": "Email",
      "form.name": "Ism",
      "form.namePh": "Sizni qanday deb chaqiraylik",
      "form.phone": "Telefon",
      "form.phonePh": "+998 __ ___ __ __",
      "form.lang": "Muloqot tili",
      "form.langRu": "Ruscha",
      "form.langUz": "O‘zbekcha",
      "form.langEn": "English",
      "form.msg": "Vazifa",
      "form.msgPh": "Qisqa: obyekt, hajm, shahar",
      "form.submit": "Hisob olish",
      "form.task": "Vazifa turi",
      "form.taskPh": "Yo‘nalishni tanlang",
      "form.taskSigns": "Yorliqlar",
      "form.taskPosm": "POSM / bosma",
      "form.taskComplex": "Kompleks bezash",
      "form.taskOther": "Boshqa",
      "form.deadline": "Istalgan muddat",
      "form.deadlinePh": "Masalan: 15 avgustgacha",
      "form.errorTask": "Vazifa turini tanlang",
      "form.successWa": "WhatsApp yozish",
      "form.successCall": "Qo‘ng‘iroq",
      "form.note": "Tugmani bosib, ma’lumotlarga rozilik berasiz. Ish vaqtida qo‘ng‘iroq qilamiz.",
      "form.errorName": "Ismni kiriting",
      "form.errorPhone": "To‘g‘ri telefon raqamini kiriting",
      "form.success": "Ariza qabul qilindi. WhatsApp yoki qo‘ng‘iroq — tezroq.",
      "midCta.1.eyebrow": "Keyingi qadam",
      "midCta.1.title": "O‘xshash natija kerakmi?",
      "midCta.1.lead": "Vazifani yozing — ish kuni ichida hisob va muddat yuboramiz.",
      "midCta.1.cta": "Hisob olish",
      "midCta.2.eyebrow": "Xavfsiz",
      "midCta.2.title": "Bitta pudratchi — maketdan montajgacha",
      "midCta.2.lead": "O‘z sex, o‘z dizayn va topshirishdan keyin qo‘llab-quvvatlash. Ish vaqtida qo‘ng‘iroq qilamiz.",
      "sticky.cta": "Ariza",
      "sticky.wa": "WhatsApp",
      "form.sending": "Yuborilmoqda…",

      "footer.tagline": "To‘liq tsikli reklama-ishlab chiqarish kompaniyasi. Filiallar butun O‘zbekiston bo‘ylab.",
      "footer.menu": "Menyu",
      "footer.services": "Xizmatlar",
      "footer.contacts": "Aloqa",
      "footer.copy": "© GIGANT MEDIA",
      "footer.note": "To‘liq tsikli reklama ishlab chiqarish · O‘zbekiston",
      "lang.label": "Sayt tili",
    },
  },
};
